### ISSUE TITLE
check command should be read-only

### ISSUE THREAD

**Issue by jeffallen** [etcd-io/bbolt#104]
I tried taking a backup of a DB file, and I made it permissions 0400 so that it could not be accidentally modified later. I wanted to run "bolt check" on it to be certain it was a good backup. I couldn't because of the permissions. I changed it to u+w and then check worked. 

https://github.com/coreos/bbolt/blob/af9db2027c98c61ecd8e17caa5bd265792b9b9a2/cmd/bolt/main.go#L202

The check command should give Open a bbolt.Options with ReadOnly == true, then checking read-only files would work.

**Comment by ahrtr** [comment]
Resolved in https://github.com/etcd-io/bbolt/pull/365. 

The fix will be included in v1.3.7
