### ISSUE TITLE
Google Appengine "bad import "syscall" in github.com/coreos/bbolt/bolt_amd64.go from GOPATH"

### ISSUE THREAD

**Issue by halink0803** [etcd-io/bbolt#109]
I built an app using bbolt and tried to deploy it using google appengine but it returned error with bbolt following message:

```
go-app-builder: Failed parsing input: parser: bad import "syscall" in github.com/coreos/bbolt/bolt_amd64.go from GOPATH
```

Anyone know how to fix this error?

**Comment by xiang90** [comment]
app engine is a sandbox which disables syscalls. i do not think we can do anything here to fix this.
