### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by ncw** [etcd-io/bbolt#112]
Can you make a new release please?

I'm having to carry over a pin to master to get this to compile for linux/mips.

https://github.com/ncw/rclone/blob/41f709e13b6b2be65b6a80357c932a1da28a10c7/Gopkg.toml#L7-L11

Thanks :-)

Nick

**Comment by gyuho** [comment]
We will do once coreos/bbolt is moved to the separate etcd-io org.

**Comment by bharathramh92** [comment]
@gyuho does it mean that the repo will be maintained by new team?

**Comment by vansante** [comment]
@gyuho I see the `coreos/bbolt` repo was moved to `etcd-io/bbolt`, can a new release be made now? :)

**Comment by gyuho** [comment]
@vansante Will do today.

**Comment by gyuho** [comment]
@ncw @vansante 
https://github.com/etcd-io/bbolt/releases/tag/v1.3.1-etcd.7 has been released.

**Comment by ncw** [comment]
@gyuho - thank you very much :-)
