### ISSUE TITLE
Does this project use semver?

### ISSUE THREAD

**Issue by jmalloc** [etcd-io/bbolt#116]
It's not clear from the releases page whether or not this library uses semver, as many of the latest would be considered "pre-releases", but there has been no "stable" version for many months. 

I realise as per the readme that the API is fixed, but please consider documenting the versioning scheme used by this library. Thanks :)

**Comment by gyuho** [comment]
Yes, we do use semantic versioning. Will document in README.

**Comment by gyuho** [comment]
Please see https://github.com/etcd-io/bbolt#project-versioning. Thanks!
