### ISSUE TITLE
MacOS: possible data loss/corruption

### ISSUE THREAD

**Issue by networkimprov** [etcd-io/bbolt#124]
fsync() on MacOS does not sync to disk; the correct sync method on MacOS is via fcntl(). Golang os.File.Sync() doesn't do this in version <= 1.11. A fix is in place for 1.12. https://github.com/golang/go/issues/26650

Replace os.File.Sync calls with a direct syscall as a workaround until Go 1.12. golang/go@be10ad7

Related: https://github.com/golang/go/issues/27415

**Comment by networkimprov** [comment]
bbolt could replace os.File.Sync calls with a direct syscall as a workaround until Go 1.12. See https://github.com/golang/go/commit/be10ad762289943638efb279fc7e04c73b8d7cee for specifics.

**Comment by patrocinio** [comment]
Hello @networkimprov,

   do you have a way to recreate this scenario?

   Thanks

**Comment by networkimprov** [comment]
Since Go 1.11 is no longer supported, this issue is probably moot.

I believe demonstrating this issue entails an OS crash or unexpected power-loss, e.g. a battery failure.
