### ISSUE TITLE
why  both t.rollback() and t.Rollback() in here?

### ISSUE THREAD

**Issue by johncming** [etcd-io/bbolt#126]
https://github.com/etcd-io/bbolt/blob/7ee3ded59d4835e10f3e7d0f7603c42aa5e83820/db.go#L653-L678

is a bug?

**Comment by HeCorr** [comment]
I think they both handle different cases..

`t.rollback()` on line [662](https://github.com/etcd-io/bbolt/blob/7ee3ded59d4835e10f3e7d0f7603c42aa5e83820/db.go#L662) seems to handle panics..

`t.Rollback()` on line [673](https://github.com/etcd-io/bbolt/blob/7ee3ded59d4835e10f3e7d0f7603c42aa5e83820/db.go#L673) seems to handle errors returned from `fn(t)` (line [670](https://github.com/etcd-io/bbolt/blob/7ee3ded59d4835e10f3e7d0f7603c42aa5e83820/db.go#L670))

**Comment by cenkalti** [comment]
By looking at git history, I see that the defer is added later to handle panic cases. Probably the first rollback is forgotten to be removed. Second rollback doesn't have any effect. I've created a PR to remove that.

**Comment by cenkalti** [comment]
Looking at again, noticed `Rollback` and `rollback` has different purpose. Sorry @HeCorr I missed your answer.
