### ISSUE TITLE
Clarification on releases

### ISSUE THREAD

**Issue by ccressent** [etcd-io/bbolt#127]
The README claims that you're using semantic versioning, so `1.3.0` should be the latest stable _release_ and `1.3.1-etcd.8` should be the latest _pre-release_. Has it really been 2 years without a stable release?

I suppose my question has been asked in #116, but the answer given there is not clear to me.

As of right now:
- your `go get` instructions would effectively get `v1.3.1-etcd.8`
- a tool like dep would get `v1.3.0`, which is the latest stable version according to the semver spec. See [section 9 of the semver spec](https://semver.org/#spec-item-9).

Which release is the latest? `1.3.1-etcd.8` or `1.3.0`?

**Comment by mwf** [comment]
+1 to the question.

`go get` with module mode detects `1.3.0` as latest stable version.
And the original repo `github.com/boltdb/bolt` even has a `1.3.1` revision.

Guys, could you please check if the original's `1.3.1` is merged to your repo and release a new version?
I think it should be known as `1.3.2` or even `1.4.0`, so noone will ever confuse it with the original 1.3.1 in future.

Thanks in advance.

**Comment by gyuho** [comment]
https://github.com/etcd-io/bbolt/releases/tag/v1.3.1-etcd.8 is the latest. We only bumped a patch version since there was no new feature.

**Comment by ccressent** [comment]
`v1.3.1-etcd.8` is the latest what? Release or pre-release?

If you intend `v1.3.1-etcd.8` to be a _release_ version, then be aware that:
1. you are not following the semantic versioning spec, as claimed in the README
2. you are breaking tools that rely on semantic versioning

To be the latest _release_ and have it automatically fetched as such by dependency management tools like `dep`, you need to call it `v1.3.1`.

Again, see [section 9 of the semver spec](https://semver.org/#spec-item-9):
>***A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version.*** Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. ***Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.*** Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

**Comment by gyuho** [comment]
@ccressent Ok, we were not aware of that spec. In the next release, we will follow that spec. Thanks.
