### ISSUE TITLE
Go 1.12 darwin performance regression

### ISSUE THREAD

**Issue by jared2501** [etcd-io/bbolt#149]
I'm using bbolt in a project that I've just upgraded to go 1.12 (from go 1.11.5). I've seen a chaos integration test go from 1 second in go 1.11.5 to 21 seconds in go 1.12. 

I'm going to investigate a little further to try and identify what exactly is taking longer, creating this issue in case anyone else notices a similar problem when upgrading.

**Comment by jared2501** [comment]
I've confirmed that this is isolated to boltdb's Update API, and only reproducible on darwin.

**Comment by jared2501** [comment]
Is it possible that https://github.com/golang/go/issues/17490 could be the cause of this?

**Comment by jared2501** [comment]
Here's an example using the bbolt simulation tests:

```
✓ jnewman@Jareds-MacBook-Pro:~/go/src/go.etcd.io/bbolt | master $ go test -run TestSimulate_1000op_1p
seed: 91464
quick settings: count=5, items=1000, ksize=1024, vsize=1024
PASS
ok  	go.etcd.io/bbolt	0.097s
✓ jnewman@Jareds-MacBook-Pro:~/go/src/go.etcd.io/bbolt | master $ go version
go version go1.11.5 darwin/amd64
✓ jnewman@Jareds-MacBook-Pro:~/go/src/go.etcd.io/bbolt | master $ go test -run TestSimulate_1000op_1p
seed: 95000
quick settings: count=5, items=1000, ksize=1024, vsize=1024
PASS
ok  	go.etcd.io/bbolt	0.086s
```

Then after I install go 1.12:

```
✓ jnewman@Jareds-MacBook-Pro:~/go/src/go.etcd.io/bbolt | master $ go version
go version go1.12 darwin/amd64
✓ jnewman@Jareds-MacBook-Pro:~/go/src/go.etcd.io/bbolt | master $ go test -run TestSimulate_1000op_1p
seed: 45000
quick settings: count=5, items=1000, ksize=1024, vsize=1024
PASS
ok  	go.etcd.io/bbolt	2.511s
```

Run on macos 10.13.6.

**Comment by jared2501** [comment]
As diagnosed on https://github.com/golang/go/issues/30497, it appears that:

- Go's fsync API prior to go 1.12 actually behaved incorrectly (!).
- In Go 1.12, it was fixed to perform a F_FULLFSYNC, which has resulted in the large performance regression.

It looks like there's likely not much that can be done here...

**Comment by WIZARD-CXY** [comment]
hmm

**Comment by xiang90** [comment]
i think it is the right thing for go to do. we used to wrap fsync for the same reason for osx in etcd.

**Comment by iwind** [comment]
On mac os x, http.Server slow down 30%!  If you want to change a API, you should also improve other APIs to ensure performance.
