### ISSUE TITLE
copy a new bucket from and to the same database file in two transaction may deadlock.

### ISSUE THREAD

**Issue by bronze1man** [etcd-io/bbolt#151]
I write a program that copy one bucket to another bucket in the same database file.
I open a read-only transaction to read all data in the source bucket, and open a lot write transactions to write data to the result bucket one by one.
This way works for 100 rows.
But it will deadlock for 1000 rows.

May relative to:
> Read-only transactions and read-write transactions should not depend on one another and generally shouldn't be opened simultaneously in the same goroutine. This can cause a deadlock as the read-write transaction needs to periodically re-map the data file but it cannot do so while a read-only transaction is open.

Know workaroud :
* Do not use open two transactions at the same time, Read same rows into memory, then write them into database, then read/write again.

I use this method in mysql to copy data from one table to another table, but It looks complex in bolt.

**Comment by ifoxhz** [comment]
"May relative to:

Read-only transactions and read-write transactions should not depend on one another and generally shouldn't be opened simultaneously in the same goroutine. This can cause a deadlock as the read-write transaction needs to periodically re-map the data file but it cannot do so while a read-only transaction is open."

That's right ,this is known  issue.   
The db.mmaplock  is not reentrant.  I also encountered the issue.
this is stack.

ct 23 10:57:43 ETSME ebox[25729]: goroutine 531 [sync.RWMutex.Lock, 58 minutes]:
Oct 23 10:57:43 ETSME ebox[25729]: runtime.gopark(0x201ee60?, 0x422adc?, 0xa0?, 0x6b?, 0x0?)
Oct 23 10:57:43 ETSME ebox[25729]: 	/home/bsy/sdk/go1.20.7/src/runtime/proc.go:381 +0xe0 fp=0x40035af8c0 sp=0x40035af8a0 pc=0x446be0
Oct 23 10:57:43 ETSME ebox[25729]: runtime.goparkunlock(...)
Oct 23 10:57:43 ETSME ebox[25729]: 	/home/bsy/sdk/go1.20.7/src/runtime/proc.go:387
Oct 23 10:57:43 ETSME ebox[25729]: runtime.semacquire1(0x40001be7c8, 0x30?, 0x3, 0x0, 0x40?)
Oct 23 10:57:43 ETSME ebox[25729]: 	/home/bsy/sdk/go1.20.7/src/runtime/sema.go:160 +0x20c fp=0x40035af920 sp=0x40035af8c0 pc=0x45859c
Oct 23 10:57:43 ETSME ebox[25729]: sync.runtime_SemacquireRWMutex(0x40035af998?, 0x4?, 0x40035af998?)
Oct 23 10:57:43 ETSME ebox[25729]: 	/home/bsy/sdk/go1.20.7/src/runtime/sema.go:87 +0x28 fp=0x40035af960 sp=0x40035af920 pc=0x474ce8
Oct 23 10:57:43 ETSME ebox[25729]: sync.(*RWMutex).Lock(0x40035afa08?)
Oct 23 10:57:43 ETSME ebox[25729]: 	/home/bsy/sdk/go1.20.7/src/sync/rwmutex.go:152 +0xf8 fp=0x40035af990 sp=0x40035af960 pc=0x484608
Oct 23 10:57:43 ETSME ebox[25729]: go.etcd.io/bbolt.(*DB).mmap(0x40001be600, 0x800b1000)
Oct 23 10:57:43 ETSME ebox[25729]: 	/home/bsy/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/db.go:329 +0x44 fp=0x40035afa40 sp=0x40035af990 pc=0xca4f04
Oct 23 10:57:43 ETSME ebox[25729]: go.etcd.io/bbolt.(*DB).allocate(0x40001be600, 0x8070101?, 0xcc)
Oct 23 10:57:43 ETSME ebox[25729]: 	/home/bsy/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/db.go:939 +0xf0 fp=0x40035afaa0 sp=0x40035afa40 pc=0xca77d0
Oct 23 10:57:43 ETSME ebox[25729]: go.etcd.io/bbolt.(*Tx).allocate(0x40003255e0, 0xcc)
Oct 23 10:57:43 ETSME ebox[25729]: 	/home/bsy/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/tx.go:498 +0x3c fp=0x40035afad0 sp=0x40035afaa0 pc=0xcb093c
Oct 23 10:57:43 ETSME ebox[25729]: go.etcd.io/bbolt.(*Tx).commitFreelist(0x40003255e0)
Oct 23 10:57:43 ETSME ebox[25729]: 	/home/bsy/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/tx.go:229 +0x70 fp=0x40035afb30 sp=0x40035afad0 pc=0xcaf130
Oct 23 10:57:43 ETSME ebox[25729]: go.etcd.io/bbolt.(*Tx).Commit(0x40003255e0)
Oct 23 10:57:43 ETSME ebox[25729]: 	/home/bsy/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/tx.go:175 +0x148 fp=0x40035afc50 sp=0x40035afb30 pc=0xcaeda8
Oct 23 10:57:43 ETSME ebox[25729]: go.etcd.io/bbolt.(*DB).Update(0x4000139220?, 0x40035afd10)

**Comment by ahrtr** [comment]
If there are enough free pages, then read and write transaction can run at the same time and will not block each other. Otherwise, it needs allocate new pages, then remap the whole file; in such case, the write transaction will be blocked until all read transactions finish.

It's by design.

You need to do this (copy data from one bucket to another) in only one write transaction.
