### ISSUE TITLE
Possible to get output in reverse and limit key foreach

### ISSUE THREAD

**Issue by rebootcode** [etcd-io/bbolt#154]
I am building a log table based on time series events.

I am storing all log based on time and prefix. 

Now, I need to get the last 100 key. Every time I do simple foreach, it loads from the top and all.

I need to restrict output to 100 and in reverse ( Last in First out ). Possible?

**Edit**: I also have "prefix" on key for filter. **Key Format:** "name-time", e.g, "github-2019-03-17-22:04:22" <- thus I need output in reverse of Time for prefix "github-"

```
var buffer bytes.Buffer
err := db.View(func(tx *bolt.Tx) error {
	b := tx.Bucket([]byte("LogT"))
	if b != nil {
		c := b.Cursor()
		prefix := []byte(name+"-")
		for k, v := c.Seek(prefix); k != nil && bytes.HasPrefix(k, prefix); k, v = c.Next() {
			buffer.WriteString("<div id='"+string(k) +"'>"+string(v)+"</div><br/>")
		}
	}
	return nil
})
if err != nil {
	buffer.WriteString("failed")
}
``

**Comment by Kvaz1r** [comment]
Maybe you can use [Last/0](https://godoc.org/github.com/etcd-io/bbolt#Cursor.Last) with [Prev/0](https://godoc.org/github.com/etcd-io/bbolt#Cursor.Prev).   

But I personally prefer using [bolthold package](https://github.com/timshannon/bolthold) for complex queries.

**Comment by rebootcode** [comment]
@Kvaz1r it's very confusing to start with the bolthold package. I plan to shift to badgerDB, it has these options in built.

Thanks & Cheers
