### ISSUE TITLE
How can I add custom storage-backed other than disk?

### ISSUE THREAD

**Issue by ghost** [etcd-io/bbolt#155]
I plan to use boltdb in webassembly and store data in html5 localstorage. But boltdb doesn't support custom storage.

**Comment by Ac2zoom** [comment]
Additionally, it appears that compilation of BoltDB to WASM fails:
`
../vendor/github.com/boltdb/bolt/bolt_unix.go:24:11: undefined: syscall.LOCK_SH
../vendor/github.com/boltdb/bolt/bolt_unix.go:26:11: undefined: syscall.LOCK_EX
../vendor/github.com/boltdb/bolt/bolt_unix.go:30:10: undefined: syscall.Flock
../vendor/github.com/boltdb/bolt/bolt_unix.go:30:48: undefined: syscall.LOCK_NB
../vendor/github.com/boltdb/bolt/bolt_unix.go:44:9: undefined: syscall.Flock
../vendor/github.com/boltdb/bolt/bolt_unix.go:44:42: undefined: syscall.LOCK_UN
../vendor/github.com/boltdb/bolt/bolt_unix.go:50:12: undefined: syscall.Mmap
../vendor/github.com/boltdb/bolt/bolt_unix.go:50:51: undefined: syscall.PROT_READ
../vendor/github.com/boltdb/bolt/bolt_unix.go:50:70: undefined: syscall.MAP_SHARED
../vendor/github.com/boltdb/bolt/db.go:101:13: undefined: maxMapSize
../vendor/github.com/boltdb/bolt/bolt_unix.go:50:70: too many errors
`
