### ISSUE TITLE
Achieving BadgerDB Levels Of Write Performance, Is It Possible?

### ISSUE THREAD

**Issue by postables** [etcd-io/bbolt#166]
Is it possible to achieve levels of performance similiar to [BadgerDB](https://github.com/dgraph-io/badger)? Recently badger had a massive mishap that broke a lot of dependent projects, and I've been looking for an alternative solution.

Currently I'm experimenting with BoltDB, and it's been pretty easy to integrate with, but performance wise it appears to be about 2x as slow as BadgerDB. For reference I'm adding a 1GB file to an nvme m.2 SSD.With Badger it takes about 40 seconds, default BoltDB settings take 87 seconds.

I was able to reduce write speed down to 73 seconds with BoltDB using `FreeListMapType` which was a solid increase, but it is still pretty slow for write speeds.

I've done some digging through the godocs, and although the configuration options are commented, it is unclear what options, and what values for those options can be used to drastically improve write performance.

**Comment by vtolstov** [comment]
Bolt uses different technologies,so you can try pebble it uses lsm too like badger

**Comment by postables** [comment]
Is it at all possible to achieve better performance? 14 seconds speed up is extremely nice simply by changing a single configuration option, but it might be nice to have a short "documentation" that describes different ways to configure BoltDB to have better performance. Pebble seems nice, but without a single release, and a pretty blatant warning on the readme to not use it, I'm a little hesitant about building applications ontop of Pebble. BoltDB is great, but ideally I'd want to squeeze some better performance out of i.

I'd be happy to piece together this "performance guideline" documentation with some guidance.
