### ISSUE TITLE
Performance difference between array loop and prefix scan

### ISSUE THREAD

**Issue by rebootcode** [etcd-io/bbolt#167]
I have a certain situation where I need to grab the value from boltdb using "`key`" from an array variable.

Now, my question is - Is there any performance difference between getting value using "for loop" from key stored in array v/s `prefix` scans?

**Comment by cenkalti** [comment]
@rebootcode If I understand your question correct, you're comparing:
- https://pkg.go.dev/go.etcd.io/bbolt#readme-foreach
- https://pkg.go.dev/go.etcd.io/bbolt#readme-prefix-scans

`ForEach` iterates on every key, thus hitting every page. On the other hand, prefix scan seeks to the page that contains the first key (using B+ tree structure), skipping every page before that. For this use case prefix scan is faster.
