### ISSUE TITLE
Is there a database change management tool for bbolt?

### ISSUE THREAD

**Issue by shandets** [etcd-io/bbolt#175]
Is there a  database change management tool for bbolt that will allow one to automate an entity model change.  For example if I am using bbolt to store Users and I change the User and how it is stored.  How can I manage this change in bbolt?

Or is there an example on how one can correctly use a struct with a migration schema-version and correctly use database migration schema-versioning?

**Comment by cenkalti** [comment]
bbolt is a low-level key-value database that does not support such feature.

You can take a look the libraries listed here if it fits your use case:
https://github.com/avelino/awesome-go#database-schema-migration
