### ISSUE TITLE
key pagination

### ISSUE THREAD

**Issue by ghost** [etcd-io/bbolt#190]
I was wondering if there was a way that I can skip keys when iterating. if I want to get the latest keys they should be at the end right? so If I set the cursor at the last key is there a way I can skip 100 keys from the last without going through those 100 then continue to iterate through from there?

**Comment by xiang90** [comment]
the api does not exist. iterating the keys in memory is fast actually. but if you want to speed up, you need to develop a new api in bboltdb to walk through non-leaf nodes in b+tree.
