### ISSUE TITLE
 Free disk space

### ISSUE THREAD

**Issue by deepch** [etcd-io/bbolt#204]
I understand correctly that if I write the data to the database, put 100 times 100 kib and delete all record, my database will weigh 100 * 100kib? Data base not free's space on disk?

**Comment by Roasbeef** [comment]
By default bolt doesn't reclaim space, you can run the compaction tool to reduce database size.

**Comment by arjunsingri** [comment]
But does boltdb reuse the space after the initial records are deleted?

**Comment by deepch** [comment]
He does not release it but can reuse it.

**Comment by ptabor** [comment]
You need to compact it to reclaim the space.

```./bbolt compact -o db.out ../etcd/default.etcd/member/snap/db```
