### ISSUE TITLE
go mod tidy failed

### ISSUE THREAD

**Issue by Creek-Shi** [etcd-io/bbolt#211]
when i run "go mod tidy"  i got this    
github.com/coreos/etcd/etcdmain imports
        github.com/coreos/etcd/etcdserver imports
        github.com/coreos/etcd/mvcc/backend imports
        github.com/coreos/bbolt: github.com/coreos/bbolt@v1.3.4: parsing go.mod:
        module declares its path as: go.etcd.io/bbolt
                but was required as: github.com/coreos/bbolt

**Comment by Nanue1** [comment]
me too

**Comment by nextvary** [comment]
me too ,how to fix it?? it troubled me two days

**Comment by ScottSun** [comment]
module declares is:  "go.etcd.io/bbol"t in go.mod
but should be: github.com/coreos/bbolt

**Comment by zelfrontial** [comment]
I ran 
`GO111MODULE=on go get -u github.com/go-swagger/go-swagger/cmd/swagger@v0.22.0`
and this error came out is it related to this ?
`go: github.com/coreos/bbolt@v1.3.4: parsing go.mod: unexpected module path "go.etcd.io/bbolt"` ?

**Comment by nicocesar** [comment]
Same here with `GO111MODULE=on go get -u go.etcd.io/etcd`

```
go get: github.com/coreos/bbolt@v1.3.3 updating to
	github.com/coreos/bbolt@v1.3.4: parsing go.mod:
	module declares its path as: go.etcd.io/bbolt
	        but was required as: github.com/coreos/bbolt

```

**Comment by Roasbeef** [comment]
Y'all need to start using `go.etcd.io/bbolt` as the import path for `bbolt`. [This commit](https://github.com/etcd-io/bbolt/commit/e65d4d5d27e82efe8e16175a11ec2f6e8067c990#diff-37aff102a57d3d7b797f152915a6dc16) changed the modules name, so everything needs to be updated accordingly if y'all want to use the latest version (`v1.3.4`).

**Comment by nicocesar** [comment]
> Y'all need to start using `go.etcd.io/bbolt` as the import path for `bbolt`. [This commit](https://github.com/etcd-io/bbolt/commit/e65d4d5d27e82efe8e16175a11ec2f6e8067c990#diff-37aff102a57d3d7b797f152915a6dc16) changed the modules name, so everything needs to be updated accordingly if y'all want to use the latest version (`v1.3.4`).

you mean go.etcd.io/etcd ...?

**Comment by liangjfblue** [comment]
me too, now i just do this. 

```replace github.com/coreos/bbolt => /home/liangjf/ljf_home/code/go_home/pkg/mod/go.etcd.io/bbolt@v1.3.4```

```/home/liangjf/ljf_home/code/go_home```  is my ```GOPATH```, now i can ```go mod tidy``` and go ```go build```

i want to find a better way

**Comment by fezho** [comment]
Add the following two replace sentences in `go.mod`, fix the issue:
```
replace github.com/coreos/bbolt v1.3.4 => go.etcd.io/bbolt v1.3.4
replace go.etcd.io/bbolt v1.3.4 => github.com/coreos/bbolt v1.3.4
```

**Comment by nicocesar** [comment]
> Add the following two replace sentences in `go.mod`, fix the issue:
> 
> ```
> replace github.com/coreos/bbolt v1.3.4 => go.etcd.io/bbolt v1.3.4
> replace go.etcd.io/bbolt v1.3.4 => github.com/coreos/bbolt v1.3.4
> ```

I'm totally new to modules in go and this was the help that I needed! thanks.

**Comment by GYF96** [comment]
> go.mod

where is the go.mod.   i just  do “go get”

**Comment by ptman** [comment]
> where is the go.mod. i just do “go get”

https://github.com/etcd-io/bbolt/blob/master/go.mod

**Comment by atavakoliyext** [comment]
> Add the following two replace sentences in go.mod, fix the issue:
>
> ```
> replace github.com/coreos/bbolt v1.3.4 => go.etcd.io/bbolt v1.3.4
> replace go.etcd.io/bbolt v1.3.4 => github.com/coreos/bbolt v1.3.4
> ```

Can anyone please explain why this works?

**Comment by Kuri-su** [comment]
because etcd upgrade `github.com/coreos/bbolt` from v1.3.1-coreos.6 to `go.etcd.io/bbolt` v1.3.3 in etcd v3.4.0, so you use `github.com/coreos/bbolt` to import `go.etcd.io/bbolt`

because the  go package name of `github.com/coreos/bbolt`  is changed, this modification is note in [`etcd v3.4.0 CHANGELOG`](https://github.com/etcd-io/etcd/blob/e2d67f2e3bfa6f72178e26557bb22cc1482c418c/CHANGELOG-3.4.md#dependency-2), it's name is `go.etcd.io/bbolt` now.  

if you import etcd before v3.4.0, Go will use `github.com/coreos/bbolt` to find package , but it will got `go.etcd.io/bbolt`, so, Go will say this: 
```
	module declares its path as: go.etcd.io/bbolt
	        but was required as: github.com/coreos/bbolt
```


you should to add a weird section in `go.mod`, or upgrade the etcd version you depend on 

```
replace github.com/coreos/bbolt v1.3.4 => go.etcd.io/bbolt v1.3.4
replace go.etcd.io/bbolt v1.3.4 => github.com/coreos/bbolt v1.3.4
```
