### ISSUE TITLE
NextSequence() for different buckets.

### ISSUE THREAD

**Issue by SkaMarius** [etcd-io/bbolt#212]
Is there a way to use NextSequence() for different buckets? 
Let's say I have different buckets for different employees: workers, managers, sales etc. I don't want their key's to duplicate. How can i solve this? or is it not possible or maybe not efficient for different buckets?

**Comment by HeCorr** [comment]
I would personally store a global value containing the next available key/user id.

So when you create a user:
1. get the next global key/id
2. increment it
3. use it for your new user

I would also implement a [Rollback](https://pkg.go.dev/go.etcd.io/bbolt#Tx.Rollback) in case something bad happens, so no ID will be skipped (a.k.a. no user would have that ID but it still incremented)
