### ISSUE TITLE
boltdb/bbolt data replication / high availability

### ISSUE THREAD

**Issue by viseth** [etcd-io/bbolt#222]
Hi,

I'm already using the cool boltdb package but I have a use case where data replication is a must have. I still want to stick with boltdb or bbolt. The KV store should support high availability mode, for instance in case instance bboltA is down instance bboltB should go up and running with exact same data as instance bboltA. Is that currently possible ?

Thanks for your insight,

BR,

Viseth

**Comment by ptabor** [comment]
Please consider using etcd (https://etcd.io/) that is a replication layer on top of bbolt.
