### ISSUE TITLE
module go.etcd.io/bbolt is wrong

### ISSUE THREAD

**Issue by kirito41dd** [etcd-io/bbolt#224]
github.com/coreos/bbolt: github.com/coreos/bbolt@v1.3.4: parsing go.mod:
        module declares its path as: go.etcd.io/bbolt
                but was required as: github.com/coreos/bbolt

**Comment by zshorz** [comment]
```
module go.etcd.io/bbolt

go 1.12

require golang.org/x/sys v0.0.0-20200202164722-d101bd2416d5
```
Change to the following？
```
module github.com/etcd-io/bbolt

go 1.12

require golang.org/x/sys v0.0.0-20200202164722-d101bd2416d5
```

**Comment by ocket8888** [comment]
Same issue here. Currently this is keeping me from migrating my own project to a Go module - is that the canonical import path? Should I not have been `go get`ing it from Github at all in the first place?

**Comment by ptabor** [comment]
etcd uses go.etcd.io domain:  https://github.com/etcd-io/etcd/blob/2b79442d8e9fc54b1ac27e7e230ac0e4c132a054/go.mod#L1 and is referenced from other packages:
  https://github.com/etcd-io/etcd/blob/2b79442d8e9fc54b1ac27e7e230ac0e4c132a054/go.mod#L41

so I would consider go.etcd.io as a canonical path.

**Comment by ptabor** [comment]
linking also with: https://github.com/etcd-io/etcd/issues/12028

**Comment by newlife** [comment]
any progress here?

**Comment by ocket8888** [comment]
The fix is to use `go.etcd.io/bbolt` as it's the canonical import path.
