### ISSUE TITLE
Open a database as read only

### ISSUE THREAD

**Issue by albertogviana** [etcd-io/bbolt#228]
Hi,

I have an application that is writing to a boltdb, and I implemented a `cli` just to display what is in boltdb. However when I run the `cli` with the `ReadOnly` flag as `true`, it will not return any result until I completely stop my systemd service. Is this an expected behavior? Or is it not possible to share a database as a read only mode?

Thank you

**Comment by aivarasbaranauskas** [comment]
It is expected. Single boltdb can be either opened by 1 process in read-write mode or multiple processes in read-only mode. [README](https://github.com/etcd-io/bbolt#read-only-mode).

**Comment by comunidadio** [comment]
Wouldn't it be possible to support opening read-only database even when one process opened it read-write? If I understand correctly a read-only database would always be consistent even when another process is writing to it (thanks to copy-on-write).

**Comment by jimisaacs** [comment]
+1 on the question asked most recently.

**Comment by xiang90** [comment]
No. It is not supported. You may improve this in theory, but currently, the implementation does not allow it.

**Comment by ptabor** [comment]
To extend on it: 
  - metadata pages (1,2) keep pointing on the b-tree root node. If the file changes the root pages keep changing. An RO reader does not know which page is root. 
  - the writer makes an arbitrary (in-memory tracking) decisions when there is 'no RO' transaction open about overriding the unreferenced pages. It will not notice there are 'file-level' readers and screw the mapping. 
  - for the same reason copying a live bbolt DB file at regular filesystem level is not an atomic operation and likely reads to the corrupted, not usable backup. For this, one need file-system with file snapshotting support.
