### ISSUE TITLE
Does BoltDB support near-duplcate-content detention?

### ISSUE THREAD

**Issue by sleshJdev** [etcd-io/bbolt#230]
I want to implement similar comment detection functionality for the comments engine which uses golang+BoltDB. The task is very similar to the Near-duplicates detection problem(which is a sort of ad-hoc text processing).

1. Does BoltDB allow Near-duplicates detection in any form?
2. If 1 is false, then what is the easiest way to achieve? I only could think k-grams + full-text search + ranking. Any better ideas?

Here are books/articles I read about the subject: [Near-duplicates and shingling][1] and [Syntactic Clustering of the Web][2]

So how does BoltDB deal with it?

Here is related SO [issue](https://stackoverflow.com/questions/63050908/does-boltdb-support-near-duplcate-content-detention)

  [1]: https://nlp.stanford.edu/IR-book/html/htmledition/near-duplicates-and-shingling-1.html
  [2]: https://www.hpl.hp.com/techreports/Compaq-DEC/SRC-TN-1997-015.pdf

**Comment by ptabor** [comment]
No. It's not something that should be handled in the physical DB layer (like bolt).
