### ISSUE TITLE
why the bbolt occupy so big memory space ?

### ISSUE THREAD

**Issue by sfwtoms2030** [etcd-io/bbolt#234]
i use bbolt mmap a database: 12.52GB， when i scan all keys in a bucket, why that occupy so big memory， around 4.92G， have someone ask this problem? just scan .
    PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
     20   0 12.520g 4.934g 4.928g S   7.3 67.6   2:49.28 main

**Comment by ahrtr** [comment]
It's expected behavior, refer to: 
https://github.com/etcd-io/bbolt#caveats--limitations

**Comment by sfwtoms2030** [comment]
is there any way that release this memory that dont use ? for example lru alogrithm  or some other method?

**Comment by ahrtr** [comment]
Note that this is an open source project, you have to get your hand dirty. 

I just finished a series of posts on bbolt, and one of which may be helpful to you: 
[click here](https://mp.weixin.qq.com/s?__biz=MzU2MjM1NTY3Mw==&mid=2247484270&idx=1&sn=72b15fb2c4ab4a43040304ced6dd6104&chksm=fc6b8fd8cb1c06cebf9e51b217ced1110098574e87e628454b7cf2b99663d393e15c572a802a&token=1942476301&lang=zh_CN#rd)

**Comment by ishan16696** [comment]
>Note that this is an open source project, you have to get your hand dirty.
> I just finished a series of posts on bbolt, and one of which may be helpful to you:
[click here](https://mp.weixin.qq.com/s?__biz=MzU2MjM1NTY3Mw==&mid=2247484270&idx=1&sn=72b15fb2c4ab4a43040304ced6dd6104&chksm=fc6b8fd8cb1c06cebf9e51b217ced1110098574e87e628454b7cf2b99663d393e15c572a802a&token=1942476301&lang=zh_CN#rd)

Hey @ahrtr,
the link you have provided for your posts is not working. I'm want to explore bbolt, can you please share your posts. TIA

**Comment by ptabor** [comment]
The link works for me. You need to translate Chinese to English. 

BTW: mmaping alone does not causes on its own growth of the reserved memory... it grows the virtual memory... but this doesn't need to occupy RAM. 

In this case, I bet that majority of memory is taken by etcd process itself and not bbolt. 
Etcd stores in memory the revision maps and parts of the WAL log.

**Comment by ahrtr** [comment]
Just as the https://github.com/etcd-io/bbolt#caveats--limitations mentioned, it's expected behavior. And no plan to make big change on this, at least in near future.
