### ISSUE TITLE
How to get the current size of the database?

### ISSUE THREAD

**Issue by austincollinpena** [etcd-io/bbolt#245]
Is it possible to get the size, in bytes, of the current database?

I found ```FreelistInuse```, but it returned half the size of what my file system says the database size is.

**Comment by schmurfy** [comment]
I was wondering that too but I wonder if the size of the database file will ever go down or if it somehow keep track of the "free" space instead that big file.

**Comment by ptabor** [comment]
Please see:  https://github.com/etcd-io/etcd/issues/12341

**Comment by schmurfy** [comment]
Thanks, really helpful read :)
