### ISSUE TITLE
How to improve performance for thousands of writes? Perfomance seems to jump from .001s per 1,000 inserts to .7s

### ISSUE THREAD

**Issue by austincollinpena** [etcd-io/bbolt#246]
I understand that bolt is best used for many reads, but when I seed my database I'm getting some weird performance.

My first couple thousand adds are incredibly fast at around .001 seconds, but eventually there is a jump all the way to .7 - .8 seconds after a couple hundred loops.

How can I debug this?

Here's my code:

```go
	err = Bdb.Update(func(tx *bolt.Tx) error {
		b := tx.Bucket([]byte("IpAddresses"))
		for i, val := range ipAdds {
			if i%1000 == 0 {
				nowTime := time.Now()
				elapsed := nowTime.Sub(lastTime).Seconds()
				lastTime = time.Now()
				fmt.Printf("Added 1000 ip addresses in %v seconds \n\n", elapsed)
			}
			err := b.Put([]byte(val.ip), []byte(val.locationCode))
			if err != nil {
				return err
			}
		}
		return nil
	})
```

**Comment by ptabor** [comment]
Can you split it to multiple transactions ?  
  - DB might be growing... 
  - tracking of free pages might get more expensive when the size grows... 
  - I would not be surprised if the cost of updates in the 'nodes'  mid transaction is n^2.

The real cost of adding happens during the Commit... that is not measured here.
