### ISSUE TITLE
Does bbolt work well on NFS?

### ISSUE THREAD

**Issue by dclong** [etcd-io/bbolt#257]
It is well know that SQLite3 has issues on NFS. Does bbolt work well on NFS or should users avoid to use it on NFS?

**Comment by hiqsociety** [comment]
I'm curious on this also.

**Comment by goodbaikin** [comment]
I was trying to share a [containerd](https://github.com/containerd/containerd)  root dir by NFS, which uses bbolt as database.
The result was no success. Node B couldn't obtain lock, as bbolt was already locked by node A.

**Comment by ptabor** [comment]
1. Definitely bbolt cannot be used in RW mode by many concurrent processes running on NFS. 
2. I can imagine bbolt being open in RO mode by many concurrent processes (but this requires testing). 
3. I don't know about any studies of bbolt behavior on NFS. Happy to learn if anyone has data or will perform tests.
