### ISSUE TITLE
invalid argument error

### ISSUE THREAD

**Issue by fpessolano** [etcd-io/bbolt#258]
I am trying to use bbolt on a mips (omega) chip with OpenWRT on it.
The code works on several platform already (32 and 64 bits) but when compiled for this combination, I get an invalid argument error when the database is opened.

Is bbolt not compatible with OpenWRt or mips? Or is there some setting tweaking needed?
Thanks.

**Comment by googolgl** [comment]
Same mistake
```# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02-SNAPSHOT'
DISTRIB_REVISION='r15932-e8cbdbbe97'
DISTRIB_TARGET='ramips/mt76x8'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 21.02-SNAPSHOT r15932-e8cbdbbe97'
DISTRIB_TAINTS='no-all no-ipv6'```

**Comment by fpessolano** [comment]
We managed to somewhat resolve it but we got to other issues. This packages seems using unsafe pointer operations that more strict OS do not like, therefore we are phasing it out.
