### ISSUE TITLE
How do you change the bucket.fillpercent ?

### ISSUE THREAD

**Issue by hiqsociety** [etcd-io/bbolt#261]
Sorry cant seem to find it obviously on search engines etc.

How do you change the bucket.fillpercent without modifying the code?

**Comment by ptabor** [comment]
It's not persisted. You set it in every transaction that writes data: 

```
b := tx.Bucket("name")
...
tmpb, berr := tmptx.CreateBucketIfNotExists(next)
...
tmpb.FillPercent = 0.9 // for seq write in for each
```
