### ISSUE TITLE
With reference to this, when or is it possible to implement compaction?

### ISSUE THREAD

**Issue by hiqsociety** [etcd-io/bbolt#268]
https://github.com/etcd-io/bbolt/issues/79

Compaction feature please. Thanks for this great software

**Comment by ptabor** [comment]
https://github.com/etcd-io/bbolt/blob/6565e9dd89355d804448c7d0ffaa7b9bbe678b3d/compact.go#L8

**Comment by hiqsociety** [comment]
Will the db size be reduced?
