### ISSUE TITLE
Fix code documentation: Apparent UB if value bytes passed to Put() are changed before committing

### ISSUE THREAD

**Issue by cjdelisle** [etcd-io/bbolt#275]
Scenario:
1. Begin transaction
2. Set value bytes to "hi"
2. Call Put(value)
3. Set value bytes to "ho"
3. Call Get() again to read back what was apparently stored
4. Get() yields "ho"

Maybe this was fixed in a later version or maybe I'm seeing things here, but I just wanted to make note of this happening because it chewed up a good 3 hours of my day. Workaround for me is to always clone value []byte, key is already cloned so no need.

**Comment by ptabor** [comment]
It's working as expected... but agree we need to improve the documentation (code comments on the API). 

We need to document that: 
 - Memory returned by Get is valid only within the transaction (see https://github.com/etcd-io/bbolt/issues/298)
 - That the returned memory is owned by bbolt and must NEVER be modified. 
    (writing to this memory might corrupt the whole page, thus the bbolt tree structure)
