### ISSUE TITLE
Data is put to the bolt, but sometimes is not available

### ISSUE THREAD

**Issue by iamatsundere** [etcd-io/bbolt#277]
Hi, I created a bucket and store key-value pairs as usual. Now my storage size is 2.1Gi. I am pretty sure that I put a pair to the database but sometimes when I get value, it is not available. So I want to ask how can I optimized this IO procedure?

**Comment by xiang90** [comment]
Can you tell us how to produce this issue?

**Comment by chanchal1987** [comment]
Please make sure to commit the transaction and close the db before existing. Also please make sure you are not putting duplicate keys.

**Comment by iamatsundere** [comment]
I found the issues, the problem is when I put data to DB, it's complicated to tell but the value is empty somehow and the key is duplicated. 

I'm also think it might come from my data is an array, so whenever I update the data, I pop it from DB then append and put it again to the db. I did a work around by putting key as a pattern and value as each item of the array. But I don't know does the DB return values following by the order I put them in?

**Comment by jimeh** [comment]
@iamatsundere From [Iterating over keys](https://github.com/etcd-io/bbolt/blob/b18879eb6c413ffda00456687e411092c2614602/README.md#iterating-over-keys) in the README:

> _Bolt stores its keys in byte-sorted order within a bucket. This makes sequential iteration over these keys extremely fast._

This means insert/write order is lost, as the order is determined based on the key itself, not the order in which keys were created. But it means you can easily iterate over keys which are related via a common prefix.

**Comment by ptabor** [comment]
Please reopen with a snipped of code to reproduce the issue.
