### ISSUE TITLE
bbolt 1.3.6 release plan

### ISSUE THREAD

**Issue by hexfusion** [etcd-io/bbolt#278]
etcd 3.5 has a dependency on a new release of bbolt (1.3.6). Starting this issue to track that process and timing.

ref: https://github.com/etcd-io/etcd/issues/12970

cc @gyuho @ptabor

**Comment by hexfusion** [comment]
@gyuho I am going to cut a new release tonight any objects or pointers to the process? I don't see an explicit version so it seems just cut a tag/release from master? Any objections?

cc @xiang90 @ptabor @jpbetz @jingyih @spzala

**Comment by gyuho** [comment]
Yes, let's cut a new release with bolt 1.3.6

**Comment by gyuho** [comment]
Released https://github.com/etcd-io/bbolt/releases/tag/v1.3.6.

Let me know if I missed anything. v1.3.6 was just cut from the current master branch.

**Comment by mrueg** [comment]
@gyuho @hexfusion seems like this was only tagged, could you promote it to a release?
