### ISSUE TITLE
How to get keys by index?

### ISSUE THREAD

**Issue by SirMetathyst** [etcd-io/bbolt#280]
I'm trying to implement pagination by having an offset and a limit but boltdb iterates through keys so how would I be able to grab a key by index instead then iterate from that key through to limit?

**Comment by ptabor** [comment]
The common solution is to store when paginating a last read key... and threat it as a 'resume' index. 

There is no 'index' based approach. And yes: -> You cannot use this technique to build 'give me the 5-th page' experience... ...but the pagination if old-school [1] ;)

[1] https://searchengineland.com/google-brings-continuous-scroll-to-desktop-search-results-390004
