### ISSUE TITLE
why tx.db.grow() is not needed in tx.root.spill()

### ISSUE THREAD

**Issue by uvletter** [etcd-io/bbolt#285]
I'm learning the source code of boltdb recently. In `Commit` `tx.root.spill()` would shift `tx.meta.pgid` possiblely when there is no enough room in `freelist`, but without a `tx.db.grow()`.  If the following freelist serialization find a feat page in the freelist, the  `tx.db.grow()` would be eliminated, is it the expected behave?
Thanks a lot

**Comment by ptabor** [comment]
It's interesting question... 

What I wanted to say is that 'grow' is postponed till tx.commitFreelist() is called: 

https://github.com/etcd-io/bbolt/blob/b654ce922133ff49bb385297f30835ca357bac5f/tx.go#L239-L240

But... the commitFreelist is only called when we are NOT operating in NoFreelistSync (that's getting more popular): 

https://github.com/etcd-io/bbolt/blob/b654ce922133ff49bb385297f30835ca357bac5f/tx.go#L174-L175

Intuitively the growing part should be migrated out of the 'commitFreelist' call.

I think it justifies an attempt to create a repro test for this issue.

**Comment by uvletter** [comment]
From the git history `grow` is introduced in https://github.com/boltdb/bolt/issues/284, to solve the issue `fdatasync` is unsafe in some particular FS and OS version. As far as I can tell this issue has been fixed in the newer Linux kernel. As a side effect `Truncate` improve the performance by mitigatethe possibility of sync the metadata when flush the dirty page.  But all the above will have no effect if `NoFreelistSync` is on...

**Comment by ahrtr** [comment]
My understanding is both `spill` and `commitFreelist` are operating on virtual memory, it's only necessary to resize the file before syncing data to db file.
