### ISSUE TITLE
.db file doesn't change after i delete half of the data

### ISSUE THREAD

**Issue by leolikescoding** [etcd-io/bbolt#288]
i insert like 1000,0000 data into the bucket, it occupy about 1.4GB disk size.
but after i delete half of the key-value ,the .db file remains to be around 1.4GB.
can anyone help to answer why the disk-size not changed after  delete ?

**Comment by mndrix** [comment]
When you delete data in bbolt, it marks the data as deleted but doesn't return the free space to the file system.  It keeps its file the same size so that it can write new data to that location when you add more data.

**Comment by leolikescoding** [comment]
@mndrix ,oh interesting , even say i  delete some thing from Bucket1 and add same thing to Bucket1 , the size keeps the same ?

**Comment by missinglink** [comment]
@leolikescoding correct, when you delete data the freed area in the file can be reused by other data but the file itself not truncated.

**Comment by ahrtr** [comment]
You can run command compact to reclaim the free space. For example,
`go run cmd/bbolt/main.go compact -o db_new db`
