### ISSUE TITLE
[QUESTION] iterator order

### ISSUE THREAD

**Issue by twiny** [etcd-io/bbolt#289]
is there a way to iterate bucket in FIFO order. the key added will be the first and so on..

```go
	for k, v := c.First(); k != nil; k, v = c.Next() {
		if err := fn(k, v); err != nil {
			return err
		}
	}
```

**Comment by ptabor** [comment]
In practice no. You would need to make time-of-adding a prefix of the key itself so benefit just from the lexicographical order. 

BTW: It's how `etcd` works... keys are the revision numbers for the consecutive modifications sorted by time.
