### ISSUE TITLE
Performance/Storage optimization question

### ISSUE THREAD

**Issue by utdrmac** [etcd-io/bbolt#296]
It is very easy to take a struct, add some json tags, marshal it, and store the bytes to a single key. Is that less efficient than storing the individual elements of the struct into their own key-pairs? See the example below if that is unclear. Maybe for smaller JSON it doesn't make a difference, but for larger/longer data, does it matter to bolt?

```
-- single JSON
  mykey: {"id":12345,"name":"Steve","age":33,"title":"Director"}

-- KV ("rows")
  12345:     # bucket
    name: Steve
    age: 33
    title: Director
```

**Comment by ptabor** [comment]
My rule of thumb: 

It's good to have a key-value pairs that are a few (N=4-20) times smaller than pageSize (4096 on linux by default), as: 
  - they don't cause page fragmentation (as ~4096/N remains unallocated on page in the worst case)
  - whenever we fetch a single bit from such value ... we need to fetch the whole page

Having values that exceed page-size is problematic... as multiple pages are allocated for such a value... and reading even a single bit... requires load of multiple pages. 

There is no point in storing individual integers... as separate KVs.
