### ISSUE TITLE
why memory is freed? Disable bolt own garbage collector

### ISSUE THREAD

**Issue by ibudisteanu** [etcd-io/bbolt#298]
```
var v []byte

db.View(func(tx *bolt.Tx) error {
	b := tx.Bucket([]byte("MyBucket"))
	v = b.Get([]byte("my_data"))
	fmt.Printf("The answer is: %s\n", v)
	return nil
})

....
....

go func(){
   time.Sleep(10 * time.Second)
   fmt.Printf("using v again: %s\n", v)
}()
```

I have noticed that sometimes v is being freed. Why is it freed? Can I disable it not being freed ?  
LE: I have updated the example.

One silly solution is to manually clone the b.Get(), but I believe it should be another solution to it. I already manually cloned the returned values and the memory is no longer freed.

**Comment by ahrtr** [comment]
The returned value is only valid for the life of the transaction. So if you want to continue read the value after the transaction is closed, you have to clone the value.

**Comment by ibudisteanu** [comment]
I have noticed it. Is there any way to disable the memory not to be forcefully freed ?

**Comment by ahrtr** [comment]
The memory isn't freed, it is just not valid any more when the transaction is closed.

**Comment by ptabor** [comment]
The main think RO transaction does, it protects pages that were valid when the transaction was open from freeing and re-use. If you really need to avoid copy... keep the RO transactions open longer... but it will come at the cost of DB size growing faster.
