### ISSUE TITLE
iterate returns duplicate keys

### ISSUE THREAD

**Issue by NorseGaud** [etcd-io/bbolt#299]
Original issue: https://github.com/boltdb/bolt/issues/632 by @xiang90

---

I expect iterating a bucket with cursor return keys in order, but it would return duplicated keys.

Here is the data

And here is the script to reproduce the problem

Here is the output:
```
key="\x00\x00\x00\x00\x00\x00\xfe\x9d_\x00\x00\x00\x00\x00\x00\x00\x00"
key="\x00\x00\x00\x00\x00\x00\xfe\x9c_\x00\x00\x00\x00\x00\x00\x00\x00"
key="\x00\x00\x00\x00\x00\x00\xfe\x9b_\x00\x00\x00\x00\x00\x00\x00\x00"
key="\x00\x00\x00\x00\x00\x00\xfe\x9a_\x00\x00\x00\x00\x00\x00\x00\x00"
duplicated key="\x00\x00\x00\x00\x00\x00\xfe\x9c_\x00\x00\x00\x00\x00\x00\x00\x00"!!!!
duplicated key="\x00\x00\x00\x00\x00\x00\xfe\x9b_\x00\x00\x00\x00\x00\x00\x00\x00"!!!!
duplicated key="\x00\x00\x00\x00\x00\x00\xfe\x9a_\x00\x00\x00\x00\x00\x00\x00\x00"!!!!
```
Am I missing something?

The key `\x00\x00\x00\x00\x00\x00\xfe\x9c_\x00\x00\x00\x00\x00\x00\x00\x00` shows up twice during cursor iterating.

**There are examples and much more in https://github.com/boltdb/bolt/issues/632 -- please go there and take a look**

**Comment by ahrtr** [comment]
I couldn't reproduce this issue using bbolt 1.3.6 on db files generated on both etcd 3.4.13 and 3.5.0. 

If you see this issue, please provide the db file and let me know the etcd version.

**Comment by NorseGaud** [comment]
@ahrtr , all information is in https://github.com/etcd-io/etcd/issues/13456

**Comment by ptabor** [comment]
All I can recommend is to follow similar investigation to: 
https://github.com/etcd-io/bbolt/issues/335
