### ISSUE TITLE
Determine free space

### ISSUE THREAD

**Issue by gibeautc** [etcd-io/bbolt#309]
I understand the mechanics of why the database file does not shrink when data is deleted from the database, but it also doesn't seem like there is a clean way to determine how much of the file is "free" I have looked through the stats and done some testing but I cant seem to make anything add up to what I would expect. 

I add 1000 rows of data, tracking actual disk size and graphing the stats.  Then I delete all those rows and still monitor the stats, obviously the disk size remains constant during this time, but I would expect someway to calculate or show that the file is essentially "empty" (i realize there is some overhead for main db structure, but even subtracting the freeAlloc bytes( closest thing that looks like what I want) from the disk file size, gives me over 2MB  "in use" for an empty database. 

Is there a clean way to calculate actual "in use" size of a database?

**Comment by gibeautc** [comment]
non issue, i figured out a way to do it.

**Comment by yonderblue** [comment]
Would you mind letting us know the way?

**Comment by gibeautc** [comment]
@yonderblue 
the inner part of the function that would determine the size: 
(I removed some parts that made up my wrapper of bbolt to avoid confusion)

var ret int64
DB.Sync()
_ = DB.Update(func(tx *bbolt.Tx) error {
   ret = tx.Size()
   return nil
})
ret -= int64(vb.DB.Stats().FreeAlloc)         
ret -= int64(vb.DB.Stats().FreelistInuse)
return ret
