### ISSUE TITLE
Detaching Fork

### ISSUE THREAD

**Issue by vidhanio** [etcd-io/bbolt#311]
GitHub support has a way to request detachment of a fork, if it has become independent enough to become its own repository. I believe that this repository fulfills those conditions, and this may be a good idea.

https://support.github.com/request/fork?tags=fork

**Comment by ahrtr** [comment]
It sounds good to me. Any comments? @ptabor @spzala @serathius

**Comment by serathius** [comment]
Sounds good

**Comment by ahrtr** [comment]
FYI. I just raised a ticket to request the detaching.

**Comment by ahrtr** [comment]
Completed. Thx @vidhanio
