### ISSUE TITLE
testing: why was cmd/bbolt/main_test.go disabled?

### ISSUE THREAD

**Issue by missinglink** [etcd-io/bbolt#314]
I noticed that the `cmd/bbolt/main_test.go` test file was disabled in https://github.com/etcd-io/bbolt/commit/b951856120dd57364e7187080f91d3d87f3c59a8 shortly after the fork to `etcd-io`.

There is no corresponding PR and no commit message as to why we might want to disable a test file, it's [still referenced in the CI config](https://github.com/etcd-io/bbolt/blob/master/Makefile#L28).

cc @gyuho do you remember why this test file was disabled, are there plans to re-enable it?

**Comment by ahrtr** [comment]
Resolved in https://github.com/etcd-io/bbolt/pull/315
