### ISSUE TITLE
Feature Request: Ability to iterate over nested buckets

### ISSUE THREAD

**Issue by davidsbond** [etcd-io/bbolt#316]
First off, thanks for maintaining the original project, I've found it simple and easy to use!

It is currently possible to iterate over all buckets at the root level on the `bbolt.Tx` type using the `ForEach` method. I have a scenario where I'd like to be able to iterate over nested buckets too. On the `bbolt.Bucket` type I'm limited to only iterating over keys with its own `ForEach` method.

If it's possible, I would like to have another method on the `bbolt.Bucket` type available like `ForEachBucket`, which allows me to iterate over nested buckets.

I wouldn't mind trying to contribute the code for this if its deemed a useful feature. Thanks!

**Comment by davidsbond** [comment]
I figured out how to do this myself just using `ForEach` and calling `Bucket` then checking for nil, I don't think a method for this needs to be added to the API now

**Comment by ptabor** [comment]
FTR: It's available now: 

https://github.com/etcd-io/bbolt/blob/b654ce922133ff49bb385297f30835ca357bac5f/bucket.go#L396
