### ISSUE TITLE
variable name is incorret

### ISSUE THREAD

**Issue by xrayw** [etcd-io/bbolt#318]
the mmap code on windows platform.

https://github.com/etcd-io/bbolt/blob/master/bolt_windows.go#L73-L75

```go
sizelo := uint32(sz >> 32)    // the variable shoud name sizehi
sizehi := uint32(sz) & 0xffffffff
h, errno := syscall.CreateFileMapping(syscall.Handle(db.file.Fd()), nil, syscall.PAGE_READONLY, sizelo, sizehi, nil)
```

it seems should be 
```go
sizehi := uint32(sz >> 32)
sizelo := uint32(sz) & 0xffffffff
h, errno := syscall.CreateFileMapping(syscall.Handle(db.file.Fd()), nil, syscall.PAGE_READONLY, sizehi, sizelo, nil)
```

**Comment by ahrtr** [comment]
Actually it's correct, but the naming is a little confusing. At first look, the `sizelo` seems to be the high 32 bits, and `sizehi` seems to be the low 32 bits; but usually windows is litten-endian, so actually `sizelo` is the low 32 bits, and `sizehi`  is the high 32 bits.

https://pkg.go.dev/golang.org/x/sys/windows#CreateFileMapping

**Comment by ahrtr** [comment]
Please let me know if you see any issue on Windows platform.
