### ISSUE TITLE
go get is deprecated and go install returns an error

### ISSUE THREAD

**Issue by MikaeelMF** [etcd-io/bbolt#319]
Hi!
I wanted to install bolt for the first time. Using the command stated in README it returned:
`go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
`
So, I found out that go get won't build packages from go version 1.18 and it is deprecated ([link](https://go.dev/doc/go-get-install-deprecation)).
Therefor I set to use `go install` instead, then I faced this error:
` $ go install github.com/etcd-io/bbolt@latest`
`go install: github.com/etcd-io/bbolt@latest: github.com/etcd-io/bbolt@v1.3.6: parsing go.mod:
	module declares its path as: go.etcd.io/bbolt
	        but was required as: github.com/etcd-io/bbolt
`

I would really appreciate it if anyone could help me with this problem.

**Comment by MikaeelMF** [comment]
I have solved the issue! The problem was with my configs! thanks!

**Comment by HannahMR** [comment]
I'm having the exact same problem, but I don't understand what you mean by configs. Which configuration did you need to adjust?

**Comment by MikaeelMF** [comment]
> I'm having the exact same problem, but I don't understand what you mean by configs. Which configuration did you need to adjust?

First make sure your Go environment is set up correctly. A good starting point is [here](https://www.digitalocean.com/community/tutorials/how-to-install-go-and-set-up-a-local-programming-environment-on-ubuntu-18-04).
Next open a terminal in the directory of your project and write this command:
`go mod init`
This will create a file named go.mod which keeps track of all necessary modules that is needed to run your program.
Then use the `go get` command and you are good to go!
P.S. [This](https://www.digitalocean.com/community/tutorials/how-to-use-go-modules) is a good introduction to `go mod` if you are interested.

**Comment by HannahMR** [comment]
Ah ha!  ...if you can't tell I'm a bit of a Go newb. This is very helpful, thanks.
