### ISSUE TITLE
test cases failing on power (ppc64le) 

### ISSUE THREAD

**Issue by adilhusain-s** [etcd-io/bbolt#322]
the test cases are failing due to page size different between power and x86.
on power the page size is 64KB instead of 4 KB. 

# failing test cases 

FAIL: TestBucket_Delete_FreelistOverflow (2613.18s)
    bucket_test.go:432: expected more than 0xFFFF free pages, got 9791

FAIL: TestBucket_Stats (62.54s)
    bucket_test.go:1222: unexpected BranchPageN: 0

FAIL: TestBucket_Stats_Large (19.84s)
    bucket_test.go:1601: unexpected BranchPageN: 1

FAIL: TestDB_Close_PendingTx_RO (0.31s)
    db_test.go:732: database did not close

bbolt version: master 
go version: 1.18
arch: pp64le 
os: linux 
distro: ubi 8.5 

could you please address the test failures?

**Comment by ptabor** [comment]
I think I fixed this for 16KB M1 pages: https://github.com/etcd-io/bbolt/pull/355

The 64KB pages are not checked... but also should not fail the test, as it should get skipped. 

Please reopen or provide an analogous PR with the values for 64KB pages.
