### ISSUE TITLE
Corrupt DB after a power failure

### ISSUE THREAD

**Issue by esaumell** [etcd-io/bbolt#325]
Hi, I would like to recover data. I'm getting a `panic: invalid freelist page: 1938, page type is leaf`. As mentioned on #135 I've tried `bbolt check host.db` but any operations with `bbolt` are giving that same error.

I thought that maybe the end of the file was corrupted and I was wondering if it would be possible to strip that corrupted data from the file.
I've tried opening the db file with an hex editor and I can read some of the data. I tried some arbitrary deletions without success.

Anyone has experience with this? Would be nice to recover at least part of the file in a working state.

**Comment by ishan16696** [comment]
yes, I have also experienced this before. Sadly till now I haven’t found any solution for this

**Comment by tmm1** [comment]
@esaumell What exception do you get from `bbolt check`?

**Comment by esaumell** [comment]
> @esaumell What exception stack trace do you get from `bbolt check`?

Hey sorry to say I no longer use the software that used bbolt as DB...

**Comment by ptabor** [comment]
For posterity: 

I recommend: 
```
./bbolt page --all --format-value=redacted data/member/snap/db
```

to diagnose the structure of the tree... and have data that after inspection can be shared with others for help (no values - just keys -> that in case of etcd, does not carry any business-data).
