### ISSUE TITLE
Missing GitHub release for v1.3.6

### ISSUE THREAD

**Issue by dolmen** [etcd-io/bbolt#326]
[v1.3.6](https://github.com/etcd-io/bbolt/releases/tag/v1.3.6) has been tagged on June 2nd 2021 (see #278), but **no GitHub release** has been made.

So the latest release displayed in the README is: [![Releases](https://img.shields.io/github/release/etcd-io/bbolt/all.svg?style=flat-square)](https://github.com/etcd-io/bbolt/releases)

This is shown [on GitHub](https://github.com/etcd-io/bbolt/blob/master/README.md#bbolt) and [on pkg.go.dev](https://pkg.go.dev/github.com/etcd-io/bbolt?utm_source=godoc#section-readme).

**Comment by ahrtr** [comment]
We start to track changes starting from v1.3.7, FYI. [CHANGELOG](https://github.com/etcd-io/bbolt/blob/master/CHANGELOG.md), and will create Github release starting from 1.3.7 as well.
