### ISSUE TITLE
[Doc] go get is deprecated

### ISSUE THREAD

**Issue by patrocinio** [etcd-io/bbolt#332]
The section https://github.com/etcd-io/bbolt#installing tells to run the following command:

``
go get go.etcd.io/bbolt/...
``

But go get is deprecate:

``
% go get go.etcd.io/bbolt/...
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
``

So I recommend using `go install` to install it.

**Comment by lknite** [comment]
```
$ go install go.etcd.io/bbolt@latest
go: downloading go.etcd.io/bbolt v1.3.6
go: downloading golang.org/x/sys v0.0.0-20200923182605-d9f96fdee20d
package go.etcd.io/bbolt is not a main package

$ bbolt
bash: bbolt: command not found

$ bolt
bash: bolt: command not found

$ sudo find / -name "bolt"

$
```

**Comment by sne4ker** [comment]
You can still use go get when doing it inside a module:

    go mod init example
    go get go.etcd.io/bbolt/...

Works with Go 1.19.2

**Comment by ahrtr** [comment]
bbolt is supposed to embedded into client applications, so you need to run go get to update the go.mod/go.sum for your client applications.
```
go get go.etcd.io/bbolt@latest
```

If you want to use the [cmd/bbolt](https://github.com/etcd-io/bbolt/tree/master/cmd/bbolt), please command below to install it,
```
go install go.etcd.io/bbolt/cmd/bbolt@latest
```
