### ISSUE TITLE
How do I drop an existing DB and start afresh

### ISSUE THREAD

**Issue by viralmutant** [etcd-io/bbolt#333]
I have an existing `boltdb` file and I need to programmatically drop the entire db during upgrade. Looking into the source code I could not find a `drop` command

How may I achieve this ?

**Comment by andreyvit** [comment]
Will `os.Remove` do what you want?

**Comment by viralmutant** [comment]
:) I was hoping if `boltdb` supports is natively.

**Comment by ptabor** [comment]
There is no drop. Either remove all the keys or create a new file.

Removing all the keys should be relatively performant. It is I expect bbolt to write only 3 pages (meta, bucket & empty leaf)... but the scan of all the keys is the cost to be paid.
