### ISSUE TITLE
Whether linux/loong64 can be supported?

### ISSUE THREAD

**Issue by zhangyongding** [etcd-io/bbolt#334]

**Comment by zhangyongding** [comment]
# go.etcd.io/bbolt
../../../pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:133:13: undeclared name maxMapSize for array length
../../../pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:422:12: undefined: maxMapSize
../../../pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:440:10: undefined: maxMapSize
../../../pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:441:8: undefined: maxMapSize
../../../pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:932:2: pos declared but not used
../../../pkg/mod/go.etcd.io/bbolt@v1.3.6/bolt_unix.go:68:15: undeclared name maxMapSize for array length
../../../pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:532:12: undefined: maxAllocSize
../../../pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:533:10: undefined: maxAllocSize
../../../pkg/mod/go.etcd.io/bbolt@v1.3.6/unsafe.go:27:12: undeclared name maxAllocSize for array length

**Comment by xen0n** [comment]
Already supported in main branch, I think upstream only needs to make a release in this case.
