### ISSUE TITLE
Feature request: gzip value

### ISSUE THREAD

**Issue by xin-tsla** [etcd-io/bbolt#344]
Hi All,
Wondering is that possible to have gzip option for storing value ?
If so, I could prepare a PR for it.

**Comment by ptabor** [comment]
gziping should be responsiblity of the consumer of bbolt. ]

I don't think we want to take any dependency and another complexity in bbolt. I also see a little benefits of gziping within bbolt (i.e. the only benefit is ability to gzip whole node if the node contains a lot of similar values) and hope it will fit in the smaller number of pages.
