### ISSUE TITLE
v1.3.7 release plans?

### ISSUE THREAD

**Issue by xen0n** [etcd-io/bbolt#353]
Hi,

What is the release plan for a v1.3.7 release? I see some changes piling up already, and especially that `linux/loong64` users are waiting for inclusion of #303 in a tagged release so a number of downstream projects (like etcd itself, and including but not limited to caddy, Gitea, and possibly many more in the Docker/CNCF ecosystem) could be unblocked.

Thanks very much for the continued maintenance of this fork!

**Comment by ahrtr** [comment]
Please read https://github.com/etcd-io/bbolt/issues/399
