### ISSUE TITLE
bbolt CLI surgery commands

### ISSUE THREAD

**Issue by ptabor** [etcd-io/bbolt#370]
After https://github.com/etcd-io/bbolt/pull/361 is submitted it would be good to expose additional bbolt file 'surgery' commands: 

 1. `bbolt surgery revert-meta-page. db.inputFile db.outputFile`
    - should execute https://github.com/etcd-io/bbolt/blob/d13096eccc8deb93488897990957a8ac82df8ada/internal/surgeon/surgeon.go#L41
   
 2. `bbolt surgery copy-page db.inputFile db.outputFile 17 14`
   - should execute https://github.com/etcd-io/bbolt/blob/d13096eccc8deb93488897990957a8ac82df8ada/internal/surgeon/surgeon.go#L10

3 `bbolt surgery write-empty-branch-page db.inputFile db.outputFile 17`
- should execute a new command that overwites given page with an empty node. 

Follow up to:  https://github.com/etcd-io/bbolt/issues/335

**Comment by ahrtr** [comment]
> `bbolt surgery write-empty-branch-page db.inputFile db.outputFile 17`
> 
>     * should execute a new command that overwites given page with an empty node.

Why don't we support `write-empty-page` so that we can overwrite whatever page (branch or leaf)?

**Comment by ahrtr** [comment]
Instead of `write-empty-page` to get rid of the whole page and all its children, it would make more sense to add the command something like `update-page-element-count` to get rid of some elements in the given page and all the children the removed elements link to.

It's exactly how previously I fixed a corrupted db file. FYI [issues/13406/main.go](https://github.com/ahrtr/etcd-issues/blob/master/issues/13406/main.go)

**Comment by ahrtr** [comment]
Note, the following commands will be included in v1.3.7,
- `bbolt surgery revert-meta-page`
- `bbolt surgery copy-page`
- `bbolt surgery clear-page`

All other changes will be included in next release, hopefully 1.4.0.

**Comment by ahrtr** [comment]
TODO: add `bbolt surgery freelist rebuild/check ...` commands.
see https://github.com/etcd-io/bbolt/pull/443#discussion_r1153404241

**Comment by ahrtr** [comment]
all surgery related commands are done.

**Comment by ahrtr** [comment]
Done.
