### ISSUE TITLE
Plan to release v1.3.7 and cut branch release-1.3

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/bbolt#399]
See the changes to be included in v1.3.7 in https://github.com/etcd-io/bbolt/pull/398.

FYI. Verified that the latest source code on master branch is working well with etcd. https://github.com/etcd-io/etcd/pull/15193

After both https://github.com/etcd-io/bbolt/pull/395 and https://github.com/etcd-io/bbolt/pull/398 are merged, we will
1. tag/release v1.3.7.
2. cut branch release-1.3, which will only merge bug fixes for 1.3.x. The master branch is for 1.4.

**Comment by ahrtr** [comment]
cc @ptabor

**Comment by ahrtr** [comment]
FYI. The integration with https://github.com/etcd-io/etcd/pull/15197 also looks good.

**Comment by ahrtr** [comment]
I think we are ready to release/tag bolt `v1.3.7` and cut `release-1.3` branch. @ptabor Please feel free to do it if you want and you don't have any objection. Otherwise, let me do it tomorrow my time.

**Comment by ptabor** [comment]
@serathius 

I don't have any objections. Thank you for the work. 

With @serathius we think that more investment in the defense-in-depth - in particular more safe-guards around access to Unsafe-mapped memory. It comes with some performance hit, but corrupted on-disk state has higher consequences than a few additional pointer comparisons.

**Comment by ahrtr** [comment]
Thanks @ptabor for the feedback.

Will release/tag bolt `v1.3.7 `and cut `release-1.3` branch today.

**Comment by ahrtr** [comment]
Done. https://github.com/etcd-io/bbolt/releases/tag/v1.3.7
