### ISSUE TITLE
Add the zvart project to readme

### ISSUE THREAD

**Issue by lazy-am** [etcd-io/bbolt#413]
Hello. I am working on a small anonymous [сhat ](https://github.com/lazy-am/zvart)and use bbolt as database. Is it possible to add my project to your readme?

**Comment by ahrtr** [comment]
Please feel free to submit a PR.

**Comment by ptabor** [comment]
I would consider whether there should be minimal 'popularity' required from the project to add it to README. 
I don't think we want to maintain 'reverse index' of all project's that link to etcd. Rather to have a list of recognizable project that can be used as argument about etcd maturity. 

As a rule of thumb I would propose a 100+ mentions (e.g. https://www.google.com/search?q=%22https%3A%2F%2Fgithub.com%2Flazy-am%2Fzvart%22) as a bar.

**Comment by ahrtr** [comment]
Basically makes sense to me. But "100+ mentions" seems a little strict :)

**Comment by lazy-am** [comment]
Okay, I'll remind you about a project in five years.
