### ISSUE TITLE
Why Bucket.Root() is exposed?

### ISSUE THREAD

**Issue by cenkalti** [etcd-io/bbolt#418]
https://github.com/etcd-io/bbolt/blob/da2f2a53f6e2f25b215b79db2cd417488ef8e955/bucket.go#L70

Is there a use case? Couldn't find anything in documentation or among existing Github issues.

**Comment by ahrtr** [comment]
It's introduced in https://github.com/etcd-io/bbolt/commit/b178373351a2d9711c8614255843038c5bed5872. The user (in this repo) of the method was gone. 

Let 's keep it as it's, because it's a public API, user application may use it.
