### ISSUE TITLE
bench: read: read seq: iter mismatch

### ISSUE THREAD

**Issue by tjungblu** [etcd-io/bbolt#428]
To reproduce run:
> go run ./cmd/bbolt/ bench -count 100000

results in:
```
starting write benchmark.
starting read benchmark.
bench: read: read seq: iter mismatch: expected 100000, got 200000
exit status 1
```

after bisecting, it seems this was introduced with https://github.com/etcd-io/bbolt/pull/420

**Comment by ahrtr** [comment]
cc @cenkalti Please take a look if you have bandwidth. Otherwise let me take care of next week.

**Comment by tjungblu** [comment]
all good, fixed this with https://github.com/etcd-io/bbolt/pull/429

I added some locking around the struct, even though it was merely the `completedOps` when reading being updated more often than expected when it is too quick.

**Comment by ahrtr** [comment]
Thanks @tjungblu . Just to double check, why did't we see it previously? Just because change the data type from int to int64 in #420?

**Comment by tjungblu** [comment]
it's not the data type, it's this block here:
https://github.com/etcd-io/bbolt/pull/420/files#diff-11c31bc30063325e6522bd9fe9048b8dd6a3e304adcd54660b72fa5ffbc5ce50L1322-L1336

you can see that the local variable `count` was replaced with `results.CompletedOps` which is updated across invocation of the whole for loop.

Happy to split this into two commits as well, I think the locking is necessary regardless...

**Comment by cenkalti** [comment]
Sorry, I haven't run the command when I resurrected the existing PR. I should have tested this more carefully.

The command still doesn't report the progress correctly. I'll take a look at this next week.
```
[dev:bbolt]{master}% go run ./cmd/bbolt/ bench -count 5000000
starting write benchmark.
Completed 0 requests, 0/s
Completed 0 requests, 0/s
Completed 0 requests, 0/s
Completed 0 requests, 0/s
Completed 0 requests, 0/s
Completed 0 requests, 0/s
Completed 0 requests, 0/s
Completed 0 requests, 0/s
Completed 0 requests, 0/s
Completed 0 requests, 0/s
Completed 0 requests, 0/s
Completed 0 requests, 0/s
Completed 0 requests, 0/s
starting read benchmark.
Completed 50000000 requests, 49983310/s
# Write 5000000(ops)    13.994756832s   (2.798µs/op)    (357398 op/sec)
# Read  55000000(ops)   1.014913368s    (18ns/op)       (55555555 op/sec)
```

**Comment by tjungblu** [comment]
> The command still doesn't report the progress correctly. I'll take a look at this next week.

True, not incrementing the counter inside the loop causes it to report zero until the end. Guess we need to add the atomic increment again to not cause any more overhead with locking in that loop (or just update the counters every n iterations) - can you please measure the overhead of that when you get to it?

**Comment by cenkalti** [comment]
After my PR #434 the output is like:
```
% go run ./cmd/bbolt/ bench -count 5000000
starting write benchmark.
Completed 1379054 requests, 1379023/s
Completed 2682759 requests, 1303324/s
Completed 3959609 requests, 1276772/s
Committing transaction...
Completed 5000000 requests, 1575320/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
starting read benchmark.
Completed 42910276 requests, 42906918/s
# Write 5000000(ops)    15.508702635s   (3.101µs/op)    (322476 op/sec)
# Read  45000000(ops)   1.048024402s    (23ns/op)       (43478260 op/sec)
```

I tried commenting out the atomic add instructions inside test loop. It didn't make any observable difference in the output.

**Comment by cenkalti** [comment]
The output above shows that most of the time is spent during commit (disk IO).

`Put` operations only modify in-memory structures, commit writes the pages to the disk.
