### ISSUE TITLE
[1.3] Support injecting failpoints to mimic syscall errors 

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/bbolt#436]
We need to backport the following PRs to release-1.3:
- [X] https://github.com/etcd-io/bbolt/pull/383 
  - The PR was merged before we created release-1.3, so it's already included in release-1.3.
- [X] https://github.com/etcd-io/bbolt/pull/400
  - https://github.com/etcd-io/bbolt/pull/439
- [X] https://github.com/etcd-io/bbolt/pull/433
  - https://github.com/etcd-io/bbolt/pull/444

**Comment by jmhbnz** [comment]
Keen to pick this one up to keep learning more about how bbolt works.  Have raised backport pr #439.

/assign @jmhbnz 

Note: @ahrtr #383 was included as needing backport above but unless I am missing something it looks like this is already done?

**Comment by ahrtr** [comment]
Thanks @jmhbnz . 

https://github.com/etcd-io/bbolt/pull/383 was merged before we created release-1.3, so it's already included in release-1.3. 

I suggest to backport #400 and #433 in two separate PRs.

**Comment by jmhbnz** [comment]
> I suggest to backport #400 and #433 in two separate PRs.

No problem, first pr updated to just reflect the first task 👍🏻

**Comment by ahrtr** [comment]
All tasks done. Thanks @jmhbnz
