### ISSUE TITLE
Flaky `testDB_Close_PendingTx`

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/bbolt#441]
FYI. https://github.com/etcd-io/bbolt/actions/runs/4527006528/jobs/7972803380

The reason could be that the [goroutine](https://github.com/etcd-io/bbolt/blob/5a7a94e5ccf07337afa3d03b436127d3e049fff0/db_test.go#L751-L754) doesn't finish in 200ms, or even doesn't get started at all in 200ms. The solution is to wait until the goroutine gets started.

```
$ git diff
diff --git a/db_test.go b/db_test.go
index db7c619..c955d28 100644
--- a/db_test.go
+++ b/db_test.go
@@ -747,12 +747,16 @@ func testDB_Close_PendingTx(t *testing.T, writable bool) {
        }
 
        // Open update in separate goroutine.
+       startCh := make(chan struct{}, 1)
        done := make(chan error, 1)
        go func() {
+               startCh <- struct{}{}
                err := db.Close()
                done <- err
        }()
 
+       <-startCh
+
        // Ensure database hasn't closed.
        time.Sleep(100 * time.Millisecond)
        select {
@@ -775,7 +779,7 @@ func testDB_Close_PendingTx(t *testing.T, writable bool) {
        }
 
        // Ensure database closed now.
-       time.Sleep(100 * time.Millisecond)
+       time.Sleep(500 * time.Millisecond)
        select {
        case err := <-done:
                if err != nil {

```

```
=== RUN   TestDB_Close_PendingTx_RO
    btesting.go:48: Opening bbolt DB at: C:\Users\RUNNER~1\AppData\Local\Temp\TestDB_Close_PendingTx_RO623935296\001\db
    btesting.go:90: Closing bbolt DB at: C:\Users\RUNNER~1\AppData\Local\Temp\TestDB_Close_PendingTx_RO623935296\001\db
    db_test.go:785: database did not close
    btesting.go:162: 
        	Error Trace:	D:/a/bbolt/bbolt/internal/btesting/btesting.go:162
        	            				D:/a/bbolt/bbolt/internal/btesting/btesting.go:78
        	            				C:/hostedtoolcache/windows/go/1.17.13/x64/src/testing/testing.go:912
        	            				C:/hostedtoolcache/windows/go/1.17.13/x64/src/testing/testing.go:1049
        	            				C:/hostedtoolcache/windows/go/1.17.13/x64/src/testing/testing.go:1253
        	            				C:/hostedtoolcache/windows/go/1.17.13/x64/src/runtime/panic.go:642
        	            				C:/hostedtoolcache/windows/go/1.17.13/x64/src/testing/testing.go:756
        	            				C:/hostedtoolcache/windows/go/1.17.13/x64/src/testing/testing.go:824
        	            				D:/a/bbolt/bbolt/db_test.go:785
        	            				D:/a/bbolt/bbolt/db_test.go:737
        	Error:      	Received unexpected error:
        	            	database not open
        	Test:       	TestDB_Close_PendingTx_RO
--- FAIL: TestDB_Close_PendingTx_RO (0.45s)
```

**Comment by cenkalti** [comment]
Is this test really necessary?

We know that `db.Begin()` and `db.Close()` both acquire the same lock, so db cannot be closed while a transaction is open. That's it.

It's hard to get guarantees from runtime about scheduling decisions. Increasing sleep durations may alleviate the problem but it's never going to fix it completely. At the same time it will make the tests slower to execute.

IMO, not everything needs to be tested if we can be sure about the behavior by reasoning.

How about removing this test completely?

**Comment by ahrtr** [comment]
I prefer to keep the test case, because it ensures `db cannot be closed while a transaction is open`. 

We can't delete a test case just because it's flaky. I agree that it's hard to completely control the runtime scheduler, but in practice we can reduce the flaky to minimum. Please let me know if you have a better solution to completely resolve it instead of just deleting it.

**Comment by cenkalti** [comment]
Then I think just increasing the first sleep duration should be enough. The purpose of `<-startCh` is not clear when looking at the code in my opinion. If you really want to put it, document its purpose and reference this GitHub issue.

The second wait can be refactored as following to make it run faster:
```
// Ensure database closed now.
select {
case err := <-done:
        if err != nil {
                t.Fatalf("error from inside goroutine: %v", err)
        }
case <-time.After(5 * time.Second):
        t.Fatal("database did not close")
}
```
