### ISSUE TITLE
Getting nil pointer deference in concurrent transactions

### ISSUE THREAD

**Issue by syedmominnaqvi** [etcd-io/bbolt#461]
Hi, I'm getting a nil pointer error sometimes when I'm running two transactions concurrently 

This is the code piece I'm referring to. The `kvs.db` is the BoltDB instance here. 
For some reason, 	`bucket := tx.Bucket([]byte(bucketName))` is returning nil sometimes on concurrent transactions.
What could be the issue?

```
func (kvs *KVStore) Put(bucketName string, key string, value interface{}) error {

	if bucketName == "" {
		return ErrBucketNameEmpty
	} else if key == "" {
		return ErrBadKey
	} else if value == nil {
		return ErrBadValue
	}

	kvs.db.Update(func(tx *bolt.Tx) error {
		_, err := tx.CreateBucketIfNotExists([]byte(bucketName))
		return err
	})

	var buf bytes.Buffer
	//used gob encoding here to make the process of serialization and deserialization effortless
	if err := gob.NewEncoder(&buf).Encode(value); err != nil {
		return err
	}

	fmt.Println(kvs)
	fmt.Println(kvs.db)

	return kvs.db.Update(func(tx *bolt.Tx) error {
		fmt.Println(tx)
		bucket := tx.Bucket([]byte(bucketName))
		fmt.Println(bucket)
		fmt.Println("db:" + tx.DB().String())
		return bucket.Put([]byte(key), buf.Bytes())
	})
}

```

**Comment by syedmominnaqvi** [comment]
It's nil

Although when I move `CreateBucketIfNotExists` into the second `kvs.db.Update()` call, I don't get the nil pointer

Also, please do note, this doesn't happen every time, but only randomly.

**Comment by syedmominnaqvi** [comment]
Seems like `c.seek(name)` in `bucket.go` is returning nil values of `k,v,flag`

**Comment by ahrtr** [comment]
Thanks @syedmominnaqvi raising this issue. A quick question, what bbolt version are you using?

**Comment by syedmominnaqvi** [comment]
I just realized I'm using the bolt library and this is bbolt. But either
way, I'm using Bolt's latest version.

**Comment by ahrtr** [comment]
@syedmominnaqvi Most likely there is a key which has the same name with the `bucketName`. Please do not ignore the second returned parameter err. If you get a nil bucket, it means the err isn't nil. Please print it. 

```
bucket, err := tx.Bucket([]byte(bucketName))
```

**Comment by syedmominnaqvi** [comment]
I'm sure there is no such key. Furthermore, bolt doesn't have a `tx.Bucket()` function that returns an error. It only returns a `*Bucket`

**Comment by ahrtr** [comment]
> Furthermore, bolt doesn't have a tx.Bucket() function that returns an error. It only returns a *Bucket

Sorry, I was going to say `tx.CreateBucketIfNotExists`.  Probably it fails sometimes due to some reason. Please do not ignore the returned error,

Change 
```
kvs.db.Update(func(tx *bolt.Tx) error {
    _, err := tx.CreateBucketIfNotExists([]byte(bucketName))
    return err
})
```

to
```
err := kvs.db.Update(func(tx *bolt.Tx) error {
    _, err := tx.CreateBucketIfNotExists([]byte(bucketName))
    return err
})

if err != nil {
    fmt.Printf("CreateBucketIfNotExists failed: %v\n", err)
}
```

**Comment by syedmominnaqvi** [comment]
I see what you're saying. But like I said, I already tried that and the
error is nil whenever the specific case occurs

**Comment by tjungblu** [comment]
took some time to write a test around this, but I can't reproduce this either. @syedmominnaqvi can you please add a reproducer for the issue?


here's my test

```go
func TestBucket_MultipleGoroutines(t *testing.T) {
	const (
		instances  = 1000
		iterations = 3000
		bucketName = "testbucket1"
		key        = "testkey"
		value      = "testvalue"
	)
	path := tempfile()
	defer os.RemoveAll(path)

	db, err := bolt.Open(path, 0600, nil)
	if err != nil {
		t.Fatalf("error from opening: %v", err)
	}

	err = db.Update(func(tx *bolt.Tx) error {
		_, err := tx.CreateBucketIfNotExists([]byte(bucketName))
		return err
	})
	if err != nil {
		t.Fatalf("error from creating bucket: %v", err)
	}

	var wg sync.WaitGroup
	errCh := make(chan error, iterations*instances)

	for instance := 0; instance < instances; instance++ {
		wg.Add(1)
		go func() {
			defer wg.Done()

			for iteration := 0; iteration < iterations; iteration++ {

				err := db.Update(func(tx *bolt.Tx) error {
					bucket := tx.Bucket([]byte(bucketName))
					if bucket == nil {
						return fmt.Errorf("bucket returned nil")
					}
					return bucket.Put([]byte(key), []byte(value))
				})
				if err != nil {
					fmt.Printf("error while running update: %v \n", err)
					errCh <- err
				}
			}
		}()
	}

	wg.Wait()

	if err := db.Close(); err != nil {
		t.Fatalf("error from closing: %v", err)
	}

	close(errCh)
	for err := range errCh {
		if err != nil {
			t.Fatalf("error from inside goroutine: %v", err)
		}
	}
}
```
