### ISSUE TITLE
Feature: Listeners

### ISSUE THREAD

**Issue by theobouwman** [etcd-io/bbolt#47]
Is there a feature to listen for changes in a collection?

**Comment by heyitsanthony** [comment]
@theobouwman no. Can you provide an example of how that would be used / what sort of interface is expected?

**Comment by theobouwman** [comment]
`.onChange(func(updagted) {
   // do stuff
})`

**Comment by heyitsanthony** [comment]
@theobouwman That looks expensive to support by default. Is there a reason why an application wouldn't be able to support this on top of bbolt as part of its txn logic? The app would cache the keys as they're put, then alert any handlers after commit.

**Comment by joeblew99** [comment]
I do that by using a message queue above bolt.
Code modules publish events to the queue, and other modules subscribe / listen for them.
Each Module is "in charge" or its part of the DB. All Modules use the same DB.

You can then extend further and have each module have its own db. Your essentially sharding the DB now. And each Module is really a Micro Service.

You can run all of these Modules and the queue in process OR split them up onto different servers.

I knwo this is not exactly what you were looking or but its far better to use a queue with pub sub pattern and let boltDB do that it does best.

**Comment by xiang90** [comment]
We could change Bucket from a go type to a go interface. Then you can easily implement a listener style feature with the same interface.

But I do not think this feature will go into the core of bbolt.

**Comment by theobouwman** [comment]
thanks
