### ISSUE TITLE
doc query re README.md

### ISSUE THREAD

**Issue by mark-summerfield** [etcd-io/bbolt#476]
In `README.md` the first example uses a mode of `0666` and the second and third examples uses a mode of `0600`, and the fourth example uses `0666` again, and the fifth `0666`. I find this confusing.

**Comment by cenkalti** [comment]
The value is not significant in example context. It determines the file mode when creating new database file on disk.

To avoid confusion for future readers, can you send a PR to fix those and set every occurrence to 0600?

**Comment by ahrtr** [comment]
We might also want to improve the doc/comment for [Open](https://github.com/etcd-io/bbolt/blob/17929157310601738759dfcd01639c309a30454c/db.go#L168-L170).

**Comment by mark-summerfield** [comment]
I've done both in PR https://github.com/etcd-io/bbolt/pull/477
