### ISSUE TITLE
Introduce stale bot

### ISSUE THREAD

**Issue by cenkalti** [etcd-io/bbolt#491]
There are many issues from past that has not been answered. I can introduce stale bot with the similar configuration of etcd repo.
https://github.com/etcd-io/etcd/blob/main/.github/stale.yml

Any comments?

**Comment by ahrtr** [comment]
Thanks @cenkalti . Sounds good to me, but I would suggest to do it after 
- we resolve the corruption issue. (top priority)
- we have cleaned up all the old issues or questions.

**Comment by cenkalti** [comment]
> we have cleaned up all the old issues or questions.

I am currently working on this. I'll iterate on existing issues and answer/close the ones that are trivial.

**Comment by ahrtr** [comment]
@cenkalti are you still working on this?

**Comment by cenkalti** [comment]
I went through the existing issues once when I first opened this one. However, I haven't really done anything since then.

**Comment by cenkalti** [comment]
However, adding a stale bot is trivial. I can send a PR this week if you're still interested.

**Comment by ahrtr** [comment]
> I can send a PR this week if you're still interested.

Yes, please.
