### ISSUE TITLE
Documentation for bbolt cli

### ISSUE THREAD

**Issue by wenjiaswe** [etcd-io/bbolt#519]
I couldn't find an official documentation on bbolt cli other than some webpages that's not from etcd/bbolt contributor (example:https://developer.hashicorp.com/vault/tutorials/monitoring/inspect-data-boltdb). I wonder if there is any effort planned to have a documentation for bbolt cli?

cc @serathius

**Comment by ahrtr** [comment]
Thanks for the suggestion, which makes sense. 

Note that there are two parts:
- Document for the basic commands. **Anyone is welcome to contribute**. I propose to add a dedicated category in etcd.io. 
- Document for the surgery commands, which are supposed to be used for advanced users only. I will take care of it after I finish analyzing all existing data corruption issues.

**Comment by ishan16696** [comment]
I can work on this, Can you please assign this to me ?

**Comment by wenjiaswe** [comment]
Thanks! @ishan16696

**Comment by ishan16696** [comment]
> Document for the basic commands. Anyone is welcome to contribute. I propose to add a dedicated category in etcd.io.

I have opened a PR: https://github.com/etcd-io/bbolt/pull/540, please take a look and feel free to ask for any change required.

>  Document for the surgery commands, which are supposed to be used for advanced users only. I will take care of it after I finish analyzing all existing data corruption issues.

I can work on this as well if no body is working on this.
