### ISSUE TITLE
ForEach and ForEachBucket

### ISSUE THREAD

**Issue by DanielAdolfsson** [etcd-io/bbolt#521]
With the introduction of ForEachBucket, I wonder if it would be a good idea to maybe exclude buckets from ForEach?

Right now, the fact that it includes buckets, is a bit unexpected. At least it was unexpected for me, seeing how there is a Delete and a DeleteBucket.

This would break code that relied on ForEach to iterate buckets though, so maybe could be a long term goal to make function more consistent. Or maybe an opt-out flag.

**Comment by ahrtr** [comment]
Points:
1. Bucket isn't the only case to return `nil` value.  Users can also put a `nil` value directly, then the returned value is also `nil` in such case. So it isn't correct to iterate on buckets by checking `value == nil`. Of course, if users are pretty sure that they will never put `nil` value, then they can do this. 
2. `ForEach` is a public API, let's keep it as it's, so as not to break any user applications.  
3. Probably we can add one more method `ForEachKey` to iterate non-bucket keys?

**Comment by cenkalti** [comment]
@ahrtr I think point 1 is not true. Even if I put `nil` as value, it is returned as empty slice when it is read.
```bash
% cat nil_test.go
package bbolt_test

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"
	bolt "go.etcd.io/bbolt"
	"go.etcd.io/bbolt/internal/btesting"
)

func TestNil(t *testing.T) {
	const bucketName = "my-bucket"

	db := btesting.MustCreateDB(t)

	saveVal := func(key, val []byte) {
		err := db.Update(func(tx *bolt.Tx) error {
			b, err := tx.CreateBucketIfNotExists([]byte(bucketName))
			if err != nil {
				return err
			}
			return b.Put(key, val)
		})
		require.NoError(t, err)
	}

	printVal := func(key []byte) {
		err := db.View(func(tx *bolt.Tx) error {
			b := tx.Bucket([]byte(bucketName))
			val := b.Get([]byte("nil"))
			fmt.Printf("val: %#v, val==nil: %v\n", val, val == nil)
			return nil
		})
		require.NoError(t, err)
	}

	saveVal([]byte("nil"), nil)
	saveVal([]byte("empty-slice"), []byte{})
	printVal([]byte("nil"))
	printVal([]byte("empty-slice"))
}
[jet:bbolt]{master}% go test -short -run TestNil
seed: 59000
quick settings: count=5, items=1000, ksize=1024, vsize=1024
val: []byte{}, val==nil: false
val: []byte{}, val==nil: false
PASS
ok  	go.etcd.io/bbolt	0.137s
```

**Comment by ahrtr** [comment]
> @ahrtr I think point 1 is not true. Even if I put `nil` as value, it is returned as empty slice when it is read.

Note that there are two cases. 
- The first one is reading the value in a separate transaction, just as you example demonstrated. You will get an empty slice. 
- The second one is reading the value in the same transaction (reading right after writing), then you will get `nil` value.

**Comment by cenkalti** [comment]
Why don't we fix this inconsistency and always return empty slice in both cases?

**Comment by ahrtr** [comment]
> Why don't we fix this inconsistency and always return empty slice in both cases?

On the contrary, I thought about always return `nil` in both cases.

**Comment by cenkalti** [comment]
Yes, `nil` makes more sense as the documentation already says `nil` will be returned for non-existent keys.
