### ISSUE TITLE
Increase the waiting time when TestDB_Open_InitialMmapSize

### ISSUE THREAD

**Issue by zhsj** [etcd-io/bbolt#54]
Origin from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832834

Since boltdb/bolt is not active, I think reporting this issue here is more appropriate.
We have the following issue,

```
--- FAIL: TestDB_Open_InitialMmapSize (5.21s)
        db_test.go:416: unexpected that the reader blocks writer
```

I think it's caused by waiting only 5s for writing 134M data. Maybe waiting more time?
At lease I didn't meet such issue if I change the time to 180s.

And someone on the origin issue complains about the test shouldn't test the hardware...

**Comment by xiang90** [comment]
Is there an easy way to reproduce this issue? If this is a true hardware related failure, we should fix the test.

**Comment by zhsj** [comment]
I think you need to test it on a slow disk...My disk is poor and run this test with 13s+

**Comment by xiang90** [comment]
@zhsj ok. probably send a PR to get this fixed?

**Comment by zhsj** [comment]
I can send a patch to increase the waiting time. But this is just a workaround, not a real fix.
Indeed, I think tests should avoid depending how good the hardware is. But I don't quite understand the corner case here and how to change the logic of the test to avoid such.
Any better idea?

**Comment by cenkalti** [comment]
Closing as it is a testing issue that only happens to be on slower hardware. It's been fixed in Debian repo with `0002-Increase-write-waiting-time-when-testing.patch` patch.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832834
