### ISSUE TITLE
On long key write loops RSS is constantly growing

### ISSUE THREAD

**Issue by slashben** [etcd-io/bbolt#541]
In our application, we monitor other processes' file activity and store the events for later processing in `bbolt`. 

In the case of specific applications, we noticed a memory-leak like behavior on our side. We have traced it back to two things:
1. Monitored applications are opening many files with random-looking names, which in our case translates to random-looking keys in boltdb. 
2. The RSS is constantly growing during the period of application monitoring, seemingly not releasing memory back to the OS

I am emulating in this the following code something that is close to what is happening in our real-life application"
```go
package main

import (
	"fmt"
	"os"
	"time"

	"github.com/google/uuid"
	bolt "go.etcd.io/bbolt"
)

func main() {
	db, err := bolt.Open("/tmp/file.db", 0644,
		&bolt.Options{
			Mlock:      false,
			NoSync:     false,
			NoGrowSync: false,
			Timeout:    0,
		})
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	defer db.Close()

	for {
		fileName := uuid.New().String()
		err = db.Update(func(tx *bolt.Tx) error {
			b, err := tx.CreateBucketIfNotExists([]byte("testbucket"))
			if err != nil {
				return fmt.Errorf("create bucket: %s", err)
			}
			err = b.Put([]byte(fileName), []byte(fileName))
			return err
		})
		if err != nil {
			fmt.Println(err)
			os.Exit(1)
		}
		// Sleep for 1 millisecond
		time.Sleep(1 * time.Millisecond)
	}

}

```

I am not sure if this is **expected** behavior or bug. 

The application I am running has memory limits and it hits memory limits rather easily 😞

**Comment by matthyx** [comment]
I am experiencing the same behavior, please have a look at fixing it. 🙏

**Comment by ahrtr** [comment]
It should be expected behaviour. Please read https://github.com/etcd-io/bbolt#caveats--limitations

```
Bolt uses a memory-mapped file so the underlying operating system handles the caching of the data. 
Typically, the OS will cache as much of the file as it can in memory and will release memory as needed
to other processes. This means that Bolt can show very high memory usage when working with large
databases. However, this is expected and the OS will release memory as needed. Bolt can handle 
databases much larger than the available physical RAM, provided its memory-map fits in the process
virtual address space. It may be problematic on 32-bits systems.
```

**Comment by fuweid** [comment]
The RSS is including page-cache. The page-cache can be reclaimed by kernel when there is no enough memory to allocate during page-fault. It's expected. If you are using cgroup v2 for the application, you can set the memory.{max, high} to force kernel reclaim the caches for anonymous memory allocation. The impact is that the read operation will be slow down.

**Comment by slashben** [comment]
> cgroup v2

Thanks for the great answer.

We are running the application on Kubernetes, do you think it is the page-cache that causes the constant bloating of the memory? 

Our application is write-heavy and reads are done sparsely (it is event logging type). Is bolt the right solution for us?

**Comment by fuweid** [comment]
Hi @slashben sorry for late reply.

> We are running the application on Kubernetes, do you think it is the page-cache that causes the constant bloating of the memory?

Based on your demo application, if you continue to insert new data, bbolt db will auto increase the db size and re-mmap the all db file. Simply, the answer is yes. Page-Cache can be reclaim by kernel if you application wants to allocate anonymous memory. However, the container should have enough memory for mmap. Let's say, the container has 10 MiB as memory limit, The bbolt db needs to re-mmap db file with 16 MiB. It will cause OOM-Killed, something like:

```
[Tue Jul 25 02:50:05 2023] Call Trace:
[Tue Jul 25 02:50:05 2023]  <TASK>
[Tue Jul 25 02:50:05 2023]  dump_stack_lvl+0x38/0x4d
[Tue Jul 25 02:50:05 2023]  dump_stack+0x10/0x16
[Tue Jul 25 02:50:05 2023]  dump_header+0x53/0x225
[Tue Jul 25 02:50:05 2023]  oom_kill_process.cold+0xb/0x10
[Tue Jul 25 02:50:05 2023]  out_of_memory+0x1dc/0x530
[Tue Jul 25 02:50:05 2023]  mem_cgroup_out_of_memory+0xf7/0x110
[Tue Jul 25 02:50:05 2023]  try_charge_memcg+0x652/0x710
[Tue Jul 25 02:50:05 2023]  ? get_page_from_freelist+0x310/0x460
[Tue Jul 25 02:50:05 2023]  charge_memcg+0x45/0xa0
[Tue Jul 25 02:50:05 2023]  __mem_cgroup_charge+0x2d/0x90
[Tue Jul 25 02:50:05 2023]  __add_to_page_cache_locked+0x2db/0x350
[Tue Jul 25 02:50:05 2023]  ? scan_shadow_nodes+0x40/0x40
[Tue Jul 25 02:50:05 2023]  add_to_page_cache_lru+0x4d/0xd0
[Tue Jul 25 02:50:05 2023]  pagecache_get_page+0x18f/0x530
[Tue Jul 25 02:50:05 2023]  ? page_cache_ra_unbounded+0x16a/0x220
[Tue Jul 25 02:50:05 2023]  filemap_fault+0x517/0xb40
[Tue Jul 25 02:50:05 2023]  ? filemap_map_pages+0x110/0x5c0
[Tue Jul 25 02:50:05 2023]  ? __schedule+0x2ca/0x8e0
[Tue Jul 25 02:50:05 2023]  __do_fault+0x3c/0x120
[Tue Jul 25 02:50:05 2023]  do_fault+0x1e9/0x470
[Tue Jul 25 02:50:05 2023]  __handle_mm_fault+0x5e5/0x970
[Tue Jul 25 02:50:05 2023]  handle_mm_fault+0xcb/0x2a0
[Tue Jul 25 02:50:05 2023]  do_user_addr_fault+0x1b5/0x640
[Tue Jul 25 02:50:05 2023]  exc_page_fault+0x71/0x160
[Tue Jul 25 02:50:05 2023]  asm_exc_page_fault+0x27/0x30
[Tue Jul 25 02:50:05 2023] RIP: 0033:0x46219d
```

So, for container, you reserve some memory size for db size even if you don't have too much read request.
Kernel has some enhancements recently for memory management, like multiple generation LRU page-reclaim. I think we don't need to worry about this in the future.

> Our application is write-heavy and reads are done sparsely (it is event logging type). Is bolt the right solution for us?

To be honest, I'm not the maintainer of bbolt. Based on my knowledge about bbolt, bbolt has improments like hashmap for freelist. It should be good for your case. However, you should have benchmark for your application~ Hope the information helps

**Comment by slashben** [comment]
> To be honest, I'm not the maintainer of bbolt. Based on my knowledge about bbolt, bbolt has improments like hashmap for freelist. It should be good for your case. However, you should have benchmark for your application~ Hope the information helps

Thanks for the explanation! This helps a lot
