### ISSUE TITLE
bbolt db is opened with file mode `0666` in many places 

### ISSUE THREAD

**Issue by ishan16696** [etcd-io/bbolt#544]
I found out that in many tests and for` bbolt cli` commands bbolt database is opened with file mode: `0666` instead of `0600`. 
1. https://github.com/etcd-io/bbolt/blob/39d812baeb46547a3adcd122c8e6110e2af0e725/internal/btesting/btesting.go#L59
2. https://github.com/etcd-io/bbolt/blob/39d812baeb46547a3adcd122c8e6110e2af0e725/tests/failpoint/db_failpoint_test.go#L25
3. https://github.com/etcd-io/bbolt/blob/39d812baeb46547a3adcd122c8e6110e2af0e725/cmd/bbolt/main.go#L211
4. in many more places

Is this intended ? if not then I can open a PR to fix this. Please let me know

**Comment by ahrtr** [comment]
thx @ishan16696 Please feel free to raise a PR to change it to 0600.
