### ISSUE TITLE
Best source for documenation??

### ISSUE THREAD

**Issue by Dracos85** [etcd-io/bbolt#55]
Is https://godoc.org/github.com/boltdb/bolt still the best place for documentation on bbolt, or is there an updated doc somewhere?  I know it was mentioned about added features since it was maintained at boltdb/bolt and I dont know if those added features are in those docs?

**Comment by jpbetz** [comment]
For bbolt, the canonical docs are https://godoc.org/github.com/coreos/bbolt

**Comment by sb10** [comment]
Is there documentation anywhere on what features were added, and about any other significant changes since the fork? Can I suggest keeping a changelog?

**Comment by cenkalti** [comment]
Documentation: https://pkg.go.dev/go.etcd.io/bbolt
Changelog: https://github.com/etcd-io/bbolt/tree/master/CHANGELOG
