### ISSUE TITLE
Problems with go version in go mod

### ISSUE THREAD

**Issue by nekohasekai** [etcd-io/bbolt#572]
Since go 1.21, if you set go version in go mod to 1.21 or above, all projects that depend on this must also use that version or above, and cannot compile on old go.

I found that the 18ebb974510c2c48f905fd4721f07a20173c6962 commit simply promoted the go version without using the features that depended on go 1.21 (I didn't double check, but unsafe.Slice exists in go 1.18 and everything compiles.). If you could consider lowering this configuration to 1.20, it would be more friendly to projects that rely on this library.

**Comment by jmhbnz** [comment]
Hi @nekohasekai - Thanks for raising this question. The `bbolt` project generally follows the same golang version policy as etcd: https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md#golang-versions 

> The etcd project aims to maintain a development branch that is on the latest [Go version](https://go.dev/dl), ideally this will align with the Go version in use for Kubernetes project development.

If you need a version of the `bbolt` library that is using an older golang release please use the latest tagged release `1.3.7` which uses go `1.17` in `go.mod`: https://github.com/etcd-io/bbolt/releases/tag/v1.3.7

You can review plans for the `1.3.8` and `1.4.0` releases here:
- https://github.com/etcd-io/bbolt/issues/542
- https://github.com/etcd-io/bbolt/issues/553
