### ISSUE TITLE
Count number of write transactions in stats

### ISSUE THREAD

**Issue by NeonWizard** [etcd-io/bbolt#575]
Stats only seems to keep count of read transactions (`Stats.TxN`, `Stats.OpenTxN`). Stats should also keep count of write transactions.

**Comment by Elbehery** [comment]
@ahrtr shall I take this ?

**Comment by ahrtr** [comment]
bbolt only supports one RW TXN at a time, so it only makes sense to add a `RWTxN` to record the total number of RW TXN which have ever started since opening the db.

**Comment by Elbehery** [comment]
Yes i investigated this and found that it makes no sense to count WTx as it is always one 👍🏽
