### ISSUE TITLE
Enhance the check command to support diagnosing a subtree

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/bbolt#580]
The whole db is indexed using b+tree. The existing [check](https://github.com/etcd-io/bbolt/blob/ef065626c30a379c5b336c96a8175abb19b78425/tx_check.go#L21) functionality checks the whole db, naming the whole tree. It would be useful if it supports checking a sub-tree, naming support checking starting from a pageId or pageId + elementId.

Based on this new feature, we will be able to know whether any sub-tree is healthy or corrupted.

**Comment by ishan16696** [comment]
Hi @ahrtr,
I can work on this, would you like to assign this issue to me ?

**Comment by ahrtr** [comment]
Thanks @ishan16696

**Comment by ahrtr** [comment]
@ishan16696 any update on this?

**Comment by ishan16696** [comment]
Hi @ahrtr ,
I've started working on this but I require some time to deliver this feature.

**Comment by ishan16696** [comment]
> naming support checking starting from a pageId or pageId + elementId.

@ahrtr  do you want to take pageID as an argument ?
```
bbolt check [Path to db] [PageID]
```

**Comment by ahrtr** [comment]
For the CMD, let's add two optional flags `--pageId` and `--elementIdx`,
```
bbolt check path-2-db --pageId <pageId> --elementIdx <elementIdx>
```

If users do not specify the pageId and elementIdx, then the default behaviour is still checking the whole db file.  Also note that it doesn't make sense only specifying `--elementIdx` if not specifying `--pageId`.

For the [(*Tx) Check](https://github.com/etcd-io/bbolt/blob/d793a651ba7d35e54a95214b007de79f520cced5/tx_check.go#L21), please get the new options/parameters included in the CheckOption, so as to be backward compatible.

**Comment by ishan16696** [comment]
> Also note that it doesn't make sense only specifying --elementIdx if not specifying --pageId.

make sense, at the same only specifying the `--pageId` can work ... right ?

**Comment by ahrtr** [comment]
> at the same only specifying the `--pageId` can work ... right ?

YES.  If only `--pageId` is specified, then we need to check all elements in the page.

**Comment by ahrtr** [comment]
any update? Please let me know if you need my assistance?

**Comment by ishan16696** [comment]
yes, I have made some progress. I have plan to work on this feature this weekend. 

>  Please let me know if you need my assistance?

thanks, I will try to open a draft PR and you can have a look.

**Comment by ahrtr** [comment]
Discussed with @ishan16696 offline, I will take over the task and @ishan16696 will continue to work on the cmd change.
- The first step: https://github.com/etcd-io/bbolt/pull/651
- Enhance the check method to support checking starting from a pageId and an elementIdx (@ahrtr will provide a draft PR) https://github.com/etcd-io/bbolt/blob/47cc272875d8c9aad6d61c51cc4fa103321e0121/tx_check.go#L34 
- Add test case to verify the change. @Elbehery  can you take care of this ?
    - Create a db file, which contains at least one branch page, and multiple leaf pages. Intentionally corrupt one of the leaf page. Verify that checking on the corrupted page will fail, while other pages should succeed
- Update cmd side change. Also add sanity test case. @ishan16696 will take care of it.

**Comment by Elbehery** [comment]
Shall i cherry pick this PR and continue atop of it ?

**Comment by ahrtr** [comment]
> * Refactor the implementation of check #651

We can merge https://github.com/etcd-io/bbolt/pull/651 directly after it being reviewed. I will raise another draft PR, then you can cherry-pick it.

**Comment by ahrtr** [comment]
> * Update cmd side change. Also add sanity test case. @ishan16696 will take care of it.

@ishan16696 Please feel free to deliver a PR to update the cmd. thx

**Comment by ahrtr** [comment]
@ishan16696 are you still interested working on this? I will take over if there is no response in this week. thx

**Comment by ahrtr** [comment]
> @ahrtr i can continue working on it

thx. Let's wait for @ishan16696 's response firstly, if there is no response this week, then please feel free to raise a PR to update the CLI.

**Comment by ishan16696** [comment]
> thx. Let's wait for @ishan16696 's response firstly, if there is no response this week, then please feel free to raise a PR to update the CLI.

I have open a PR. Please have a look.

**Comment by ahrtr** [comment]
Does anyone have bandwidth and be interested in resolve comment below?

https://github.com/etcd-io/bbolt/pull/698#issuecomment-1962937281

cc @Elbehery @ivanvc

**Comment by Elbehery** [comment]
@ahrtr on me 👍🏽

**Comment by ivanvc** [comment]
@ahrtr, are we fine re-implementing as a cobra-style command? We know that pflags are not compatible with Go-native flags (as they're not POSIX compliant).

**Comment by ahrtr** [comment]
> @ahrtr, are we fine re-implementing as a cobra-style command? We know that pflags are not compatible with Go-native flags (as they're not POSIX compliant).

It should be ok as long as there is no any behaviour change from users' perspective.

**Comment by Elbehery** [comment]
@ahrtr hello ✋🏽 

Shall i work on this or @ivanvc  will do ?

**Comment by ahrtr** [comment]
> @ahrtr hello ✋🏽
> 
> Shall i work on this or @ivanvc will do ?

Please feel free to work on it, since @ivanvc already thumbed up your comment above https://github.com/etcd-io/bbolt/issues/580#issuecomment-2037758557

**Comment by ivanvc** [comment]
Sorry for the confusion @Elbehery. Yes, my thumbs up meant that I ACK'd that you would work on it. I just wanted to confirm the decision to migrate the command to cobra-style :v:

**Comment by Elbehery** [comment]
i rasied https://github.com/etcd-io/bbolt/pull/723 to fix https://github.com/etcd-io/bbolt/issues/580#issuecomment-2037745977

**Comment by ahrtr** [comment]
We still need to enhance the `bbolt check` command to support the flag `--pageId`.  Please refer to https://github.com/etcd-io/bbolt/pull/698#issuecomment-1962937281

cc @Elbehery @ivanvc

**Comment by Elbehery** [comment]
@ahrtr raised https://github.com/etcd-io/bbolt/pull/737

**Comment by ahrtr** [comment]
All done. Thanks all.
