### ISSUE TITLE
Setup workflow running on arm64

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/bbolt#583]
Refer to https://github.com/etcd-io/etcd/pull/16801

**Comment by jmhbnz** [comment]
@ahrtr Can you please create the "contribfest" label for `etcd-io/bbolt`, I think this issue would be a great candidate for the upcoming etcd contribfest at kubecon 🙏🏻

**Comment by ahrtr** [comment]
done @jmhbnz

**Comment by ivanvc** [comment]
Can I be assigned to this one?
