### ISSUE TITLE
Bbolt weirdly formatted output when listing keys of a bucket when keys are numbers rather than strings

### ISSUE THREAD

**Issue by jo-chemla** [etcd-io/bbolt#588]
Hi there, just tried using **bbolt** to read the buckets and keys of a [portainer](https://github.com/portainer/portainer) bolt database. 

I'm using latest bbolt v1.3.7 (also tried with 1.3.5 and 1.3.3), 
 - `stats` and `buckets` listing commands both work perfect (see sample below)
 - but `keys` listing (of the `stacks` bucket) yields a weird result as described in this [portainer issue](https://github.com/orgs/portainer/discussions/10516#discussioncomment-7392741).

Is there any explanation? Using [boltbrowser](https://github.com/br0xen/boltbrowser) and it does display both the buckets entries and `stacks` keys perfectly. 

It turns out any bucket where keys are strings are correctly interpreted by bbolt, but any bucket where keys are numbers yield this weirdly interpreted output. 

```bash

C:\portainer>bbolt.exe buckets portainer.db
api_key
...
stacks
tags
...
webhooks

C:\portainer>bbolt.exe keys portainer.db stacks



(
.
9
```

EDIT: when trying to get object with key 14 of the bucket stacks, then the bbolt command returns this result, so this might have to deal with bad interpretation of keys as strings/char arrays instead of numbers/ints

```bash
C:\portainer>bbolt.exe get portainer.db stacks 14
Error key not found for key: "14." hex: "3134"
```

**Comment by jo-chemla** [comment]
Note, this boltbrowser closed issue seem strongly related: https://github.com/br0xen/boltbrowser/issues/34 although it concerns bucket names rather than keys (issue title: `Bucket names as byte-encoded integers produces unreadable UI`)

**Comment by ahrtr** [comment]
FYI. https://github.com/etcd-io/bbolt/blob/d094cd712c9ab8ffe16680c4d18dd51b24f84d2b/cmd/bbolt/main.go#L533

cc @Elbehery

**Comment by Elbehery** [comment]
👍🏽  @ahrtr  on it 👍🏽

**Comment by Elbehery** [comment]
@ahrtr  I raised https://github.com/etcd-io/bbolt/pull/590 

there is no test case for func 
```
func formatBytes(b []byte, format string) (string, error) 
``` 
to fix as well

**Comment by jo-chemla** [comment]
Thanks for spotting the issue, indeed keys were interpreted as bytes instead of hex. And thanks for opening the PR to fix it so quickly!

```bash
> bbolt keys --format hex portainer.db stacks
000000000000000e # corresponds to key with int id 14 in boltbrowser
...
0000000000000039 # corresponds to key with int id 57
```

2 follow-up questions: 
 - Should the `FORMAT_MODES` constant also include integer type? 
 - Would it make sense to also allow for passing the `format` flag to the `bbolt get` command? This way I would be able to query object at given key via the key hex value. Right now, here is the output: 
```bash
> bbolt get --format hex portainer.db stacks 000000000000000e
Error key not found for key: "000000000000000e" hex: "30303030303030303030303030303065"
```

**Comment by ahrtr** [comment]
Please also update the readme.

**Comment by Elbehery** [comment]
Will do tonight 🙏🏽

**Comment by jo-chemla** [comment]
Thanks for working on this! By the way, what would be the way to get the correct bucket keys when these keys are integers, following this fix? 

When I install the latest bbolt via `go install go.etcd.io/bbolt/cmd/bbolt@latest` and try the command with `bbolt keys --format bytes portainer.db stacks` with any format in `auto|ascii-encoded|hex|bytes|redacted`, then I never get the correct keys like in boltbrowser. This might have to do with the fact that these keys are indeed integers and that format is not yet part of the `FORMAT_MODES` variable? Thanks again for your help.

**Comment by ahrtr** [comment]
We just changed the default output format from `ascii-encoded` to `auto`, so that it will output hex string if the value isn't printable. We don't support output integer directly for now. If you really care about it, you can either (call bbolt API programatically and do whatever conversion you want) or (convert the hex string outputted by bbolt CMD).

https://github.com/etcd-io/bbolt/blob/2b3dc46d02ebf740c7e203b7a5180e5ad70d5eaa/cmd/bbolt/main.go#L1580-L1587

**Comment by ahrtr** [comment]
done

**Comment by jo-chemla** [comment]
Thanks for getting back. Installing bbolt using the last commit, then indeed the keys printed are hex in my case - so it is correctly using `auto` rather than `ascii-encoded`: 

```bash
>go install go.etcd.io/bbolt/cmd/bbolt@049c7a34157db20f8db53ef996f352cfaca691d9
>bbolt keys portainer.db stacks
000000000000000e
0000000000000011
0000000000000012
```

The only missing piece in my case is that I cannot use the `bbolt get` command with a `hex key` (or with an int key, but hex would already be great since it can be listed by `bbolt keys`) - or at least I have not found how to do it: 

```bash
>bbolt get portainer.db stacks 000000000000000e
Error key not found for key: "000000000000000e" hex: "30303030303030303030303030303065"

>bbolt get --format hex portainer.db stacks 000000000000000e
Error key not found for key: "000000000000000e" hex: "30303030303030303030303030303065"

>bbolt get portainer.db stacks 14
Error key not found for key: "14" hex: "3134"
```

**Comment by ahrtr** [comment]
>bbolt get --format hex portainer.db stacks 000000000000000e
Error key not found for key: "000000000000000e" hex: "30303030303030303030303030303065"


Please try 
```
bbolt get --parse-format hex portainer.db stacks 000000000000000e
```

**Comment by jo-chemla** [comment]
Just edited my previous message indeed, thanks for the great feedback and work on this feature!
