### ISSUE TITLE
Backport `concurrent_test.go` to `release-1.3` branch

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/bbolt#599]
This year we have created and made a number of improvements to `concurrent_test.go`, however these new tests are only in the `master` branch currently so we should backport these new tests to the stable `release-1.3` branch.

This should be a straightforward backport where the entire file should just be able to be copied as is to the `release-1.3` branch.

**Comment by Richabanker** [comment]
I would like to take this up!

**Comment by ahrtr** [comment]
Completed in https://github.com/etcd-io/bbolt/pull/600
