### ISSUE TITLE
Create a workflow template to be shared by both arm64 and non-arm64 workflow tests

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/bbolt#603]
Refer to https://github.com/etcd-io/bbolt/pull/601#issuecomment-1801525559

**Comment by ahrtr** [comment]
cc @Elbehery

**Comment by Elbehery** [comment]
Thanks a lot 🙏🏽🙏🏽🙏🏽

**Comment by Elbehery** [comment]
@ahrtr could you please assign me ?
