### ISSUE TITLE
Use `GOMEMLIMIT` instead of `GOGC` to limit GitHub test workflow memory

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/bbolt#609]
Currently, the tests GitHub workflow has a comment to switch to `GOMEMLIMIT` from `GOGC` once the project uses a greater version than Go 1.19 (https://github.com/etcd-io/bbolt/blob/master/.github/workflows/tests-template.yml#L45-L50). The current Go version is now 1.21, but the command was never updated to use `GOMEMLIMIT`.

**Comment by ivanvc** [comment]
Can you assign me to this issue? Thanks.

**Comment by jmhbnz** [comment]
Assigned - good spotting @ivanvc!
