### ISSUE TITLE
Attempting to insert into bucket crashes on `tx.allocate()`

### ISSUE THREAD

**Issue by telephrag** [etcd-io/bbolt#613]
**Prerequisites**
I keep connection to database inside structure on which handlers are called. Inside handlers I do operations with database.

```
type Env struct {
    repo *db.Conn
    // ...
}

func (e *Env) HandleSomething() error {
    // ...
    e.repo.Insert([]byte("somewhere"), []byte("atsome"), []byte("something"))
    // ... 
}
```

I run Alpine Linux 3.18 as my desktop environment if it's relevant.

I have the following method inserting records into desired bucket.
```
func (repo *Conn) Insert(bucket, k, v []byte) error {
	return repo.conn.Update(func(tx *bbolt.Tx) error {
		bkt := tx.Bucket(bucket)
		if bkt == nil {
			return bbolt.ErrBucketNotFound
		}

		if err := bkt.Put(k, v); err != nil {
			return fmt.Errorf("failed to put %s into bucket %s: %w",
				string(v),
				bucket,
				err,
			)
		}

		fmt.Println("lol same issue")
		return nil
	})
}
```
Database connection is created correctly with the database file given 0666 permissions.

**Expected behavior**
Records are inserted normally.

**Actual behavior**
As it appears in the debugger insertion operation breaks on `*Tx.allocate()` called inside `*Tx.commitFreeList()`. Note, that the same function doesn't fail when creating a bucket. 

Edit: Looked a bit deeper. It crashes on `*Tx.db.allocate()` called inside `*Tx.allocate()`.

I can post more once I get back home tomorrow. Writing this from an airport.

**Comment by ahrtr** [comment]
Have you figured out the root cause?

- What's the bbolt version?
- What's the error message?

**Comment by telephrag** [comment]
> Have you figured out the root cause?
> 
>     * What's the bbolt version?
> 
>     * What's the error message?

- `bbolt 1.38`
- Sadly no error message. It just silently stops the program execution without terminating it.

As of time when I closed the issue I found out that it may somehow work and insert records normally although couldn't figure out why so, it might be something else in my code. On the other hand the issue persisted when using two different libraries (for writing telegram bots since, that's what I'm using `bbolt` for this time) so, it might be not.

**Comment by ahrtr** [comment]
Could you provide detailed & completed steps to reproduce this issue?

**Comment by telephrag** [comment]
Not really. I can compile code pieces where it worked and where it didn't into a single program for your convenience. 

Also, I've just tried running older projects of mine where bbolt is used in the same manner and it works perfectly there so, as I said it might not even be an issue with bbolt itself.

Please, write back if you are still interested in looking into this.

**Comment by ahrtr** [comment]
ok, thx for the clarification.
