### ISSUE TITLE
Limit running arm64 tests GitHub workflow to this repository

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/bbolt#619]
With the addition of the arm64 tests, it doesn't have a limitation to just run on pushes to `etcd-io/bbolt`. Therefore, for pushes to other forks, it tries to run the tests, which eventually get canceled by GitHub and trigger a failure email notification.

It needs an if condition like the one in the main etcd repo (https://github.com/etcd-io/etcd/blob/main/.github/workflows/tests-template.yaml#L18).

**Comment by ivanvc** [comment]
Can I get assigned to this ticket? Thanks

**Comment by jmhbnz** [comment]
Good catch @ivanvc, assigned thanks!
