### ISSUE TITLE
Panic == crashes

### ISSUE THREAD

**Issue by lkarlslund** [etcd-io/bbolt#62]
I see several panic() calls in the code, but absolutely no recover() stuff. As you can not recover another module's code, you're prone to you process dying if 1) you have a faulty database or 2) there are errors in the boltdb/bbolt code somewhere.

We're using boltdb in our software, and it runs on a large number of machines - pretty reliably. But sometimes, bad stuff does happen, and the application crashes in the boltdb code somewhere.

Shouldn't everything be so reliable that it doesn't bring your entire application down with it?

**Comment by gyuho** [comment]
Was there any panic in bbolt? Even Go standard packages have tons of panics.

**Comment by lkarlslund** [comment]
We haven't switched to bbolt, so I cannot say. But using latest boltdb, yes we do get panics (often) due to boltdb, in the boltdb functions.

The places where the Go standard packages panics, is typically where you have a unrecoverable panic situation. It seems fair enough that you get a crash if there is an internal error in the garbage collector etc.

But a malformed database file hardly reason to panic. I would think that returning some sort of error would be more in its place.

**Comment by KerwinKoo** [comment]
agree with @lkarlslund .

**Comment by ahrtr** [comment]
Please provide detailed call stack when you see any panic again.
