### ISSUE TITLE
Enable GitHub workflows for PRs with the ok-to-test label

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/bbolt#631]
Allow to run GitHub workflows for Pull Requests with the `ok-to-test` label using the prow bot command /ok-to-test. This was already done in the etcd repo (refer to the issue https://github.com/etcd-io/etcd/issues/16956 and its PR https://github.com/etcd-io/etcd/pull/16965).

**Comment by jmhbnz** [comment]
Thanks @ivanvc - I'll assign this to you as discussed during the fortnightly etcd triage meeting today 🙏🏻 

/assign @ivanvc
