### ISSUE TITLE
Question about Batch vs Update

### ISSUE THREAD

**Issue by chuongle** [etcd-io/bbolt#633]
Can someone please explain to me what is the right way to use Batch call? I read the documentation but I'm not sure that I understand it completely. Here are 4 different versions that I have tested with: 

Example 1:
```go
func main() {
  for i: = 0; i < 5; i++ {
    go write()
  }
}

func write() {
  db, err := bbolt.Open("bbolt/data.db", 0600, &bbolt.Options{Timeout: 10 * time.Second})

  if err != nil {
    log.Println("errr create db: ", err)
  }

  defer db.Close()

  start := time.Now()

  // insert 60 rows
  for _, result := range results {
    err = db.Update(func(tx *bbolt.Tx) error {
      b := tx.Bucket([]byte("Bucket"))
      err = b.Put([]byte(result.ID), []byte(result.Name))
      if err != nil {
        return fmt.Errorf("error inserting data")
      }

      return nil
    })
  }

  if err != nil {
    log.Println("Error: ", err)
  }

  log.Println("insert Time: ", time.Since(start))
  // insert Time:  263.801375ms
}

``` 

Example 2:
```go
func write() {
  db, err := bbolt.Open("bbolt/data.db", 0600, &bbolt.Options{Timeout: 10 * time.Second})

  if err != nil {
    log.Println("errr create db: ", err)
  }

  defer db.Close()
  start := time.Now()

  // insert 60 rows
  for _, result := range results {
    err = db.Batch(func(tx *bbolt.Tx) error {
      b := tx.Bucket([]byte("Bucket"))
      err = b.Put([]byte(result.ID), []byte(result.Name))
      if err != nil {
        return fmt.Errorf("error inserting data")
      }

      return nil
    })
  }

  if err != nil {
    log.Println("Error: ", err)
  }

  log.Println("insert Time: ", time.Since(start))
  // insert Time:  972.034458ms
}
```

Example 3:
```go
func write() {
  db, err := bbolt.Open("bbolt/data.db", 0600, &bbolt.Options{Timeout: 10 * time.Second})

  if err != nil {
    log.Println("errr create db: ", err)
  }

  defer db.Close()
  start := time.Now()

  // insert 60 rows
  err = db.Update(func(tx *bbolt.Tx) error {
    b := tx.Bucket([]byte("Bucket"))
    for _, result := range results {
      err = b.Put([]byte(result.ID), []byte(result.Name))
      if err != nil {
        return fmt.Errorf("error inserting data")
      }
    }

    return nil
  })

  if err != nil {
    log.Println("Error: ", err)
  }

  log.Println("insert Time: ", time.Since(start))
  // insert Time:  5.866083ms
}
```
Example 4:

```go
func write() {
  db, err := bbolt.Open("bbolt/data.db", 0600, &bbolt.Options{Timeout: 10 * time.Second})

  if err != nil {
    log.Println("errr create db: ", err)
  }

  defer db.Close()
  start := time.Now()

  // insert 60 rows
  err = db.Batch(func(tx *bbolt.Tx) error {
    b := tx.Bucket([]byte("Bucket"))
    for _, result := range results {
      err = b.Put([]byte(result.ID), []byte(result.Name))
      if err != nil {
        return fmt.Errorf("error inserting data")
      }
    }

    return nil
  })

  if err != nil {
    log.Println("Error: ", err)
  }

  log.Println("insert Time: ", time.Since(start))
  insert Time:  15.364625ms
}
```

As you can see, example 1 and 2 have `for` loop wrap outside of `Update/Batch` and example 3 and 4 have `for` loop inside `Update/Batch` call. Example 1 and 2 are much slower than 3 and 4. I guess this is because you have to open a transaction per loop vs open one transaction and loop through all to insert data? 

For my application that I am working on to learn bbot, There would be concurrent calls to insert data to database. Per call, it can insert between 1 to 1000 data. Can someone give me an example when and where is the right way to use Batch? Based on my example 3 and 4, 3 is faster than 4. So maybe I misunderstood something. Also, because of this, I have to open and close db on every single concurrent call. Is that ok? or should I find a way to use one single service to open the db (but never close). and route all my write call to that service for it to insert?

FYI: I am pretty much beginner to go and trying to learn. If this is not the right place to ask question, please feel free to close the issue and direct me to the right place.

**Comment by cenkalti** [comment]
Opening and closing database on each operation is unnecessary overhead. You can use a single database instance concurrently from multiple goroutines.

Batch is only useful if it is being called by multiple goroutines concurrently.

Usage is simple. Just replace the `Update` call with `Batch` but be aware of the caveat mentioned here:
https://github.com/etcd-io/bbolt#batch-read-write-transactions

**Comment by chuongle** [comment]
@cenkalti Thank you for your reply!

> Batch is only useful if it is being called by multiple goroutines concurrently.
>
If I understand correctly, I did correctly in example 4 right? (calling write using goroutine and write using Batch). But why would the `Batch` takes longer than `Update`. Or does it take longer but using less memory? I apologize if my questions are dumb :)

**Comment by cenkalti** [comment]
No, your questions are not dumb. `Batch` is taking longer than `Update` because it waits 10 milliseconds for other goroutines to be able to combine multiple updates as a single transaction. Example 4 seems correct (after you move open/close db to outside of `write` func).

Normally, when you use `Update` it acquires a lock inside to ensure only one goroutine can write to the database. If you call `Update` from multiple goroutines, they wait previous calls to finish before acquiring the write lock again. This operation can become a bottleneck if this is a write-heavy application. `Batch` is invented to workaround this problem. When you use `Batch`, if a page gets modified in multiple goroutines, it only gets written to disk once as opposed to multiple writes as in `Update`.

**Comment by chuongle** [comment]
Thank you for clearing up my questions! I will close the issue now.
