### ISSUE TITLE
Nominate @fuweid as a bbolt reviewer

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/bbolt#648]
Hi all, I'd like to nominate @fuweid as a reviewer of bbolt, reasons,

- he has deep understanding on bbolt;
- great contribution to bbolt, especially the recent [robustness test for bbolt](https://github.com/etcd-io/bbolt/pull/628), and continuous hard work on the investigation on data corruption issue together with me;
- continuous & active reviewing PRs in bbolt (and also etcd).

Sponsored by
- @ahrtr 
- @jmhbnz 
- @ptabor 
- @serathius 
- @spzala 

cc  @jmhbnz @mitake @ptabor @serathius @spzala @wenjiaswe

**Comment by ahrtr** [comment]
Also @fuweid is actually already a reviewer of etcd, and a de-fact reviewer of bbolt.

**Comment by ptabor** [comment]
Great. +1 from me.

**Comment by serathius** [comment]
+1, thanks @fuweid for all your work.

**Comment by fuweid** [comment]
Thanks @ahrtr @ptabor @serathius for that support!

**Comment by ahrtr** [comment]
> Thanks @ahrtr @ptabor @serathius for that support!

@fuweid Please raise a PR to add you as a reviewer into the OWNERs file.

**Comment by wenjiaswe** [comment]
+1, great job @fuweid and really appreciate your contribution in etcd! And this is a great successful story of mentorship program, @ahrtr thank you for your mentorship and leadership here!

**Comment by ahrtr** [comment]
Resolved in https://github.com/etcd-io/bbolt/pull/649

**Comment by fuweid** [comment]
Thanks @wenjiaswe  @spzala !
