### ISSUE TITLE
Crash when writing data to database

### ISSUE THREAD

**Issue by 0ZeroCN** [etcd-io/bbolt#653]
Exception has occurred: fatal error
"fault"
Stack:
	 2  0x0000000000ae811a in go.etcd.io/bbolt.(*DB).meta
	     at C:/Users/myuser/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:948
	 3  0x0000000000ae3e08 in go.etcd.io/bbolt.(*DB).hasSyncedFreelist
	     at C:/Users/myuser/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:330
	 4  0x0000000000af6b37 in go.etcd.io/bbolt.(*Tx).rollback
	     at C:/Users/myuser/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:278
	 5  0x0000000000af6009 in go.etcd.io/bbolt.(*Tx).Commit
	     at C:/Users/myuser/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:161
	 6  0x0000000000ae6a6b in go.etcd.io/bbolt.(*DB).Update
	     at C:/Users/myuser/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:748
![Snipaste_2023-12-28_16-04-30](https://github.com/etcd-io/bbolt/assets/24308380/b523e1d3-4be7-43b0-b00d-5395f9510212)

data.db size:  3.00 GB (3,221,225,472 字节)

data:
"...kbGwNCjIwMTUvMDcvMTggIDIxOjA4ICAgICAgICAgICAgMTMsNjY0IGFwaS1tcy13aW4tY3J0LWZpbGVzeXN0ZW0tbDEtMS0wLmRs...+185668 more"

**Comment by 0ZeroCN** [comment]
It’s no problem for me to write small data

**Comment by ahrtr** [comment]
This issue has already been fixed in 1.3.7+. FYI. https://github.com/etcd-io/bbolt/pull/362

Please add a log at line 169 to double confirm the error,
https://github.com/etcd-io/bbolt/blob/47cc272875d8c9aad6d61c51cc4fa103321e0121/tx.go#L168-L171

**Comment by 0ZeroCN** [comment]
error log output：
mmap allocate error: truncate: truncate H:\Server\data.db: There is not enough space on the disk.

Is this problem caused by insufficient remaining disk capacity?
![Uploading Snipaste_2023-12-28_19-15-38.jpg…]()

**Comment by 0ZeroCN** [comment]
![Uploading Snipaste_2023-12-28_19-15-38.jpg…]()

**Comment by 0ZeroCN** [comment]
I know the reason, thank you！！

> This issue has already been fixed in 1.3.7+. FYI. #362
> 
> Please add a log at line 169 to double confirm the error,
> 
> https://github.com/etcd-io/bbolt/blob/47cc272875d8c9aad6d61c51cc4fa103321e0121/tx.go#L168-L171

**Comment by ahrtr** [comment]
> There is not enough space on the disk.

Yes, this seems the reason.
