### ISSUE TITLE
Recommendation for multiple random read/write structure

### ISSUE THREAD

**Issue by chuongle** [etcd-io/bbolt#669]
I have an CLI application using [cobra](https://github.com/spf13/cobra). There are command `internal1` and command `internal2` and command `database`. Potentially, `internal1` and `internal2` can both call command `database read --params` and `database write --params` at anytime to read or write data.

I realize that using this structure, I can't really support a good singleton database instance. The only way I can somewhat achieve this is having a `database init` command where it open the db, never close and return the db as a accessible variable for other commands. But I don't think it's the right approach.

The other solution is in the read/write command, I will open db, do the transaction, and close db. However this will cause the db to open and close multiple times. If I know ahead of time I need to write multiple records, I can open once, batch them and close it. But what if I only need to write one record and a time and random time. During that time, there might be some reads happening. What is the best approach for this?

Sorry for the long paragraph, just want to provide some context. 
FYI: I am pretty much beginner to go and trying to learn

**Comment by chuongle** [comment]
Once solution I am testing right now is having some sort of priority queue where I prioritize important transactions first and group lower priority transactions together so i can batch it.

Please let me know if there are better approach. Thanks!

**Comment by ahrtr** [comment]
> But what if I only need to write one record and a time and random time. During that time, there might be some reads happening

Do you mean that you want the read transaction can read the latest data even the write transaction hasn't committed yet? If YES, then you need to handle it in your application layer, e.g. sync the write buffer and the reader buffer (similar to what etcd does).

It's totally up to application's design/implementation.
