### ISSUE TITLE
A Love Letter

### ISSUE THREAD

**Issue by ambaxter** [etcd-io/bbolt#670]
Hello,

What started as a desire to learn the raft algorithm via etcd turned into an effort to gain a deep understanding of bbolt as well as databases in general. I have learned a great deal from this project. That learning turned into an obsession where I spent the last few months implementing [bbolt in Rust](https://github.com/ambaxter/bbolt-rs). For now, I've completed most core functionality. I'm slowly, but surely, working on the rest now that the holidays are over. 

I just wanted to say thank you for developing and maintaining such a wonderful and simple piece of code to learn from. 

Adam

**Comment by ahrtr** [comment]
Thanks for the info.
