### ISSUE TITLE
Rollback when freelist == pgidNoFreelist causes panic (index out of range)

### ISSUE THREAD

**Issue by jeffkayser2** [etcd-io/bbolt#70]
I am getting an error using bbolt, where meta has a valid page number, but sometimes, has the sentinal value 0xFFFFFFFFFFFFFFFF.  Sample debugging output:

bolt: db: meta: meta0: *bolt.meta,&{3977042669 2 4096 0 {3 0} 4 5 10 8200348871670262819}, meta1: *bolt.meta,&{3977042669 2 4096 0 {3 0} 2 5 11 110609177022752452}, db.meta0.txid: bolt.txid,10, db.meta1.txid: bolt.txid,11

bolt: db: meta: meta0: *bolt.meta,&{3977042669 2 4096 0 {4 0} 18446744073709551615 5 12 15793416151478272846}, meta1: *bolt.meta,&{3977042669 2 4096 0 {3 0} 2 5 11 110609177022752452}, db.meta0.txid: bolt.txid,12, db.meta1.txid: bolt.txid,11

end-case logic needs to be added, in case the freelist pageid is the sentinal value.

**Comment by jeffkayser2** [comment]
I would attempt to change it myself, but I'm not sure what the correct logic should look like.

**Comment by jeffkayser2** [comment]
// meta retrieves the current meta page reference.
func (db *DB) meta() *meta {
        // We have to return the meta with the highest txid which doesn't fail
        // validation. Otherwise, we can cause errors when in fact the database is
        // in a consistent state. metaA is the one with the higher txid.

        fmt.Printf("bolt: db: meta: meta0: %T,%v, meta1: %T,%v, db.meta0.txid: %T,%v, db.meta1.txid: %T,%v\n",
                db.meta0,db.meta0,db.meta1,db.meta1,db.meta0.txid,db.meta0.txid,db.meta1.txid,db.meta1.txid)

        metaA := db.meta0
        metaB := db.meta1
        if db.meta1.txid > db.meta0.txid {
                metaA = db.meta1
                metaB = db.meta0
        }

        // Use higher meta page if valid. Otherwise fallback to previous, if valid.
        if err := metaA.validate(); err == nil {
                return metaA
        } else if err := metaB.validate(); err == nil {
                return metaB
        }

        // This should never be reached, because both meta1 and meta0 were validated
        // on mmap() and we do fsync() on every write.
        panic("bolt.DB.meta(): invalid meta pages")
}

**Comment by jeffkayser2** [comment]
Suggested change in tx.go:

func (tx *Tx) rollback() {
        if tx.db == nil {
                return
        }
        if tx.writable {
                tx.db.freelist.rollback(tx.meta.txid)
                currFreelist := tx.db.meta().freelist
                if currFreelist != pgidNoFreelist {
                        tx.db.freelist.reload(tx.db.page(currFreelist))
                }
        }
        tx.close()
}

The above change fixed my particular issue, but I have no idea if the logic is correct.

**Comment by WIZARD-CXY** [comment]
@jeffkayser2 will be fixed, sorry take so long...

**Comment by ahrtr** [comment]
Resolved. Please try with the latest source code.
