### ISSUE TITLE
Can not distinguish between "does not exist" and "has no value"

### ISSUE THREAD

**Issue by ceving** [etcd-io/bbolt#726]
I wrote the [pwned passwords](https://github.com/HaveIBeenPwned/PwnedPasswordsDownloader) into a bucket. Because I only need to know if the hash exists, I wrote an empty value into the bucket.

```
err := hashes.Put(hash, []byte{})
```

Now I tried to find a hash, but I had to realize that [Go does not distinguish between an empty array and `nil`](https://stackoverflow.com/a/44305910/402322). The problem is: Bolt returns `nil` to indicate that a key does not exist. This is a problem because of Go's limitation. 

How to store keys without values in order to check just for existence?

I think [Bucket.Get](https://pkg.go.dev/go.etcd.io/bbolt#Bucket.Get) needs to return an additional boolean or Bucket needs an additional function to check just for existence.

[Go itself](https://go.dev/blog/maps) also indicates the existence of a key in a map by an additional boolean:
```
i, ok := m["route"]
```

**Comment by ahrtr** [comment]
For the case of "does not exist", `bucket.Get` returns `nil`.  

For the case "has no value", `bucket.Get` returns `[]byte{}`, which is obviously not `nil`.

The only known minor problem is that even you write a `nil` value for a key, when you read it back in a separate transaction, it still returns `[]byte{}`.

**Comment by ahrtr** [comment]
For example,

```
func TestBucket_Get_NonExistent(t *testing.T) {
	db := btesting.MustCreateDB(t)

	if err := db.Update(func(tx *bolt.Tx) error {
		b, err := tx.CreateBucket([]byte("widgets"))
		if err != nil {
			t.Fatal(err)
		}
		return b.Put([]byte("foo"), nil)
	}); err != nil {
		t.Fatal(err)
	}

	db.View(func(tx *bolt.Tx) error {
		b := tx.Bucket([]byte("widgets"))
		if v := b.Get([]byte("foo")); v != nil {
			t.Fatal("expected nil value")  // The test case will fail here.
		}
		return nil
	})
}

```

**Comment by ahrtr** [comment]
In short, no matter what value you write into bbolt, when you read it back, you will always get `[]byte{}` as long as `len(value) == 0` is `true`.

The only exception is that when you write a `nil` value, and you will still get a `nil` value when you read it back in the same transaction.

Will raise a PR to add a known issue.

**Comment by ahrtr** [comment]
Completed in https://github.com/etcd-io/bbolt/pull/730
