### ISSUE TITLE
Extend the maintainers of bbolt

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/bbolt#755]
As discussed in the etcd sig leads meeting also based on the activity/contribution, let's extend the bbolt's maintenance team members,
- @tjungblu is a de-fact reviewer, so propose to add @tjungblu as a formal reviewer in the top level OWNERS file;
- Add an OWNERS file under cmd/bbolt,  add the existing maintainers/reviewer as approvers and propose to add @Elbehery @ivanvc as reviewers.

cc @fuweid @jmhbnz @serathius @spzala  @wenjiaswe

**Comment by Elbehery** [comment]
+1 LGTM 

Herzlichen Glückwunsch @tjungblu  :) :)

**Comment by fuweid** [comment]
Thanks for sharing this information.

LGTM!

**Comment by jmhbnz** [comment]
+1 - Well done team, this is great news for bbolt 👍🏻

**Comment by ivanvc** [comment]
Thanks for the reviewer nomination. I'm happy to continue contributing with my expertise to the project.

**Comment by wenjiaswe** [comment]
+1 Thanks for your continuous contribution! Well deserved! @tjungblu @ivanvc @Elbehery

**Comment by tjungblu** [comment]
Thank you folks! Much appreciated :)
