### ISSUE TITLE
blob: can bolt support read/write blob data

### ISSUE THREAD

**Issue by vipally** [etcd-io/bbolt#76]
Current data access API assume all data is in memory
func (b *Bucket) Put(key []byte, value []byte) error
func (b *Bucket) Get(key []byte) []byte

Compare with other embeded db (like sqlite, berkerlydb),
read/write blob( maybe larger than 4GB) is a common demand.
I hope bolt can add APIs to open blob tx.

**Comment by simar7** [comment]
I'm also interested in knowing if there is any interest in this.
