### ISSUE TITLE
Open blocks even the ReadOnly option is set

### ISSUE THREAD

**Issue by graugans** [etcd-io/bbolt#782]
Am I using the package in a wrong way?

```go
		db, err := bbolt.Open(filename, 0600, &bbolt.Options{
			ReadOnly: true,
			Timeout:  3 * time.Second,
		})

```

When I try to read from a Docker bbolt Database while the Docker process is running I do run in a timeout
```sh
dockerdb-reader-linux-arm64 /var/lib/docker/volumes/metadata.db
Opening database file: /var/lib/docker/volumes/metadata.db
Error: could not open database file: timeout
```

With the Docker daemon being stopped it works

```sh
systemctl stop docker
Warning: Stopping docker.service, but it can still be activated by:
  docker.socket
root@ovp81x-68-26-c7 (productive):~# /tmp/dockerdb-reader-linux-arm64 /var/lib/docker/volumes/metadata.db
Opening database file: /var/lib/docker/volumes/metadata.db
Parsing database file: /var/lib/docker/volumes/metadata.db
{
  "volumes": {
    "ifm3d_share": "{\"Name\":\"ifm3d_share\",\"Driver\":\"local\",\"Labels\":{},\"Options\":{\"device\":\"/home/root/share\",\"o\":\"bind\",\"type\":\"none\"}}"
  }
}
```

**Comment by ahrtr** [comment]
The docker process holds an exclusive lock (`syscall.LOCK_EX`) on the db file, so other processes may not be able to open the db file anymore, even they are just a readonly process, which needs to hold an shared lock (`syscall.LOCK_SH`) on the db file.

**Comment by graugans** [comment]
> The docker process holds an exclusive lock (`syscall.LOCK_EX`) on the db file, so other processes may not be able to open the db file anymore, even they are just a readonly process, which needs to hold an shared lock (`syscall.LOCK_SH`) on the db file.

Thanks a lot for clarifying this.
