### ISSUE TITLE
compaction, for > 1MB values

### ISSUE THREAD

**Issue by glycerine** [etcd-io/bbolt#79]
Its great to see coreos/bbolt take up the boltdb project.

I wonder if you have already added compaction, e.g. to allow values over 1MB and not consume infinite disk space due to fragmentation?  Some time back I made a fork that did this, so the code is already available--

https://github.com/bigboltdb/bolt

>Bigboltdb is a fork of boltdb that supports database compaction and thus can store big values (over 1MB).
>
>Writing big values causes fragmententation of the backing file, requiring regular compaction to avoid infinite file growth. Bigboltdb provides a Compact() api call to do this, and a mechanism to establish regular, automatic compaction by setting the db.CompactAfterCommitCount field.
>
>Other than this one change, bigboltdb is simple, friendly fork of boltdb.

**Comment by xiang90** [comment]
@glycerine We implemented the defrag bit inside etcd. The current implementation is naive in a sense that it simply rewrites the backing file out of place in a stop-the-world fashion. There is some discussion going on inside etcd to make the defrag options concurrent by writing new values to two places during the defrag, and returning to normal write once the defrag finished.

**Comment by xiang90** [comment]
If there is a strong need from other bbolt users, we might decide to move the defrag call into bbolt itself.

**Comment by brk0v** [comment]
Talking about compaction it would be good to have:

```
func (*Tx) CopyWithCompaction(...)
func (*Tx) CopyFileWithCompaction(...)
```

Something like https://github.com/bmatsuo/lmdb-go/blob/master/lmdb/mdb.c#L9254 but for transaction not env. So it will be possible create online backup and make swap in runtime with compacted file.

**Comment by glycerine** [comment]
@brk0v It turns we run out of memory if we try to do a big compaction in one transaction.  You can see how it is done in batches in bigboltdb, but still while holding a global write lock.

https://github.com/bigboltdb/bolt/commit/c35705e85d862eb9abd4ed10bcbaf50f8c2fa25a

**Comment by brk0v** [comment]
Thank you, @glycerine for an answer.

Yes, I see what you'r doing. But I asked for something else. I need a way to write content of a transaction to a file with compaction. It's not about making compact for current db in runtime, it's for better backup purposes for example.

**Comment by thomasf** [comment]
I would like a Compact method very much as well..

Logging configuration could maybe be implemented some other way?
 
Maybe a single function returning some struct with a stringer instead?

```go
func (db *DB) Compact(batchSizeBytes int64)  (CompactReport, error) 
```

**Comment by simar7** [comment]
+1 for a Compact method.

**Comment by glycerine** [comment]
> But I asked for something else.

@brk0v then your request if off-topic here. Open a new, separate, distinct issue for a distinct concern.

**Comment by deepch** [comment]
+1 for a Compact method.

**Comment by ptabor** [comment]
Isn't this already done ?

https://github.com/etcd-io/bbolt/blob/6565e9dd89355d804448c7d0ffaa7b9bbe678b3d/compact.go#L8 ?

**Comment by cenkalti** [comment]
It's done.
