### ISSUE TITLE
Pin GitHub action dependencies

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/bbolt#800]
It came to my attention with PR #795 that I noticed that some GitHub action dependencies are pinned with the commit SHA while others aren't. I think we should standardize, also in terms of security (ref: etcd-io/etcd#18362).

The downside is that it may trigger more dependabot version bumps for every patch and the minor version released.
@ahrtr, do you have any objections against pinning the dependencies?

**Comment by ahrtr** [comment]
Thanks for raising this. It's accepted to pin by hash since it's cleared clarified in https://github.com/etcd-io/etcd/issues/18362
