### ISSUE TITLE
bbolt cli: Inspect command missing in cmd/bbolt/main.go

### ISSUE THREAD

**Issue by 0x0000F1** [etcd-io/bbolt#820]
was the inspect command in the cli removed on purpose? or is it just missing from main.go? because the command functionality exists in command_inspect.go it's just not added to the switch statement in main.go

**Comment by ahrtr** [comment]
See https://github.com/etcd-io/bbolt/blob/ee5b5967b6a97048b0a7c45b71a78f1136ee9fba/cmd/bbolt/command_root.go#L22

**Comment by 0x0000F1** [comment]
> See
> 
> https://github.com/etcd-io/bbolt/blob/ee5b5967b6a97048b0a7c45b71a78f1136ee9fba/cmd/bbolt/command_root.go#L22

...

check cmd/bbolt/main.go

the command isn't registered there and so it's inaccessible bbolt cli throws uknown command if you try to use it

**Comment by ahrtr** [comment]
Read https://github.com/etcd-io/bbolt/blob/ee5b5967b6a97048b0a7c45b71a78f1136ee9fba/cmd/bbolt/main.go#L65-L73

Also for some background, read https://github.com/etcd-io/bbolt/issues/472

Also next time raise a question in https://github.com/etcd-io/bbolt/discussions if you have any confusion.

**Comment by 0x0000F1** [comment]
> Read
> 
> https://github.com/etcd-io/bbolt/blob/ee5b5967b6a97048b0a7c45b71a78f1136ee9fba/cmd/bbolt/main.go#L65-L73
> 
> Also for some background, read #472
> 
> Also next time raise a question in https://github.com/etcd-io/bbolt/discussions if you have any confusion.

ok, can you point where in the run function is the inspect command?

https://github.com/etcd-io/bbolt/blob/ee5b5967b6a97048b0a7c45b71a78f1136ee9fba/cmd/bbolt/main.go#L111

try running the cli yourself instead maybe that should help you figure it out.

as the docs clearly state the command should work as described in the cli's readme

### inspect
- `inspect` inspect the structure of the database.
- Usage: `bbolt inspect [path to the bbolt database]`

yet its is missing in the switch statement.

in the usage function also you can clearly see inspect command being listed

https://github.com/etcd-io/bbolt/blob/ee5b5967b6a97048b0a7c45b71a78f1136ee9fba/cmd/bbolt/main.go#L151

and here's a snippet of myself trying to run the command using the cli that was installed using the latest version

```sh
$ bbolt inspect my.db
unknown command
```

hope this makes it clearer, sorry for the inconvenience as from your response it seems that you weren't happy about this being brought to your attention.

and for your info I did check the other closed issues prior to making this one.

Have a nice day.

**Comment by 0x0000F1** [comment]
and just like I thought there's nothing about this on the discussions  either :)

**Comment by Carel3DS** [comment]
The inspect command still missing: No references in the help screen but it is referenced in the documentation

**Comment by ahrtr** [comment]
> ```shell
> $ bbolt inspect my.db
> unknown command
> ```

Execute commands below on `main` branch or put the `bbolt` into `$PATH`,

```
$ go build ./cmd/bbolt/
$ ./bbolt inspect my.db
```
