### ISSUE TITLE
add new func , return  root

### ISSUE THREAD

**Issue by icetech233** [etcd-io/bbolt#827]
file   tx.go   add code 

```
func (tx *Tx) RootBucket() Bucket {
	return tx.root
}

```

**Comment by ahrtr** [comment]
Do you have real use case for this request?

We intentionally do not expose the root bucket. It (the root bucket) is invisible to users. It means users can't operate the root bucket directly, i.e. write data into the root bucket directly. It's similar to that you can't write a RDMS database directly, you must create a table firstly.

**Comment by mxmauro** [comment]
Sorry for reviving this:

@icetech233  -> `tx.Cursor().Bucket()`

@ahrtr is there any limitation on writing key/values on the root? In a RDMS yes, you create tables but in key/value stores like Redis and RocksDB to mention some, buckets are not mandatory.

**Comment by ahrtr** [comment]
> [@ahrtr](https://github.com/ahrtr) is there any limitation on writing key/values on the root?

There is no limitation technically. I don't think bbolt supports it in the first place.

**Comment by mxmauro** [comment]
Ahhh undestand. Thanks for the answer.
