### ISSUE TITLE
Cursor.Last() doesn't return the last key entered.

### ISSUE THREAD

**Issue by baxiry** [etcd-io/bbolt#842]
Hello all

When I restart my app, I need to retrieve the last key saved. It works fine up until the 9th key. After that, it can't retrieve new keys. For example, if I enter the key "10" and then close my app, when I restart it, it returns the key "9."

Cursor.Last() doesn't return the last key entered.

```go
func main() {
	db, err := bbolt.Open("mydb.db", 0600, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	id := 0

	err = db.View(func(tx *bbolt.Tx) error {
		bucket := tx.Bucket([]byte("myBucket"))
		if bucket == nil {
			return fmt.Errorf("no buckets")
		}
		c := bucket.Cursor()  // here
		key, _ := c.Last()       // or here
		k, _ := strconv.Atoi(string(key))
		id = k
		fmt.Println("last key is: ", id)

		return nil
	})
	if err != nil {
		fmt.Println(err)
	}

	err = db.Update(func(tx *bbolt.Tx) error {
		bucket, _ := tx.CreateBucketIfNotExists([]byte("myBucket"))

		k := strconv.Itoa(id + 1)

		bucket.Put([]byte(k), []byte("vaule"+k))
		fmt.Println("insert: ", k, "vaule"+k)
		return nil
	})

	if err != nil {
		fmt.Println(err)
	}
}
```

Please run `go run main.go` 10 times

## version: 
go.etcd.io/bbolt v1.3.11

Thanks

**Comment by baxiry** [comment]
I see the problem.

Bolt's byte order is different from number order. The last key for it is the largest byte. Not the last key entered.

The question becomes: Is there a way to know the last key entered? Not the largest key?

Thanks

I expect that converting numbers to bytes directly and skipping the string stage will be a good solution for me.

**Comment by ahrtr** [comment]
All keys are sorted automatically in ascending order. In your case, []byte("9") is bigger than []byte("10"), so the last key was  []byte("9"). But if you converting numbers directly to []byte, then obviously []byte(10) is bigger than []byte(9).

**Comment by baxiry** [comment]
@ahrtr Yes You are right, that was my problem.
 I think having the feature of getting the last key and not the biggest key would be a useful feature. Especially when the keys are not in a logical order. Like words.
Thanks for your great work.

**Comment by ahrtr** [comment]
> I think having the feature of getting the last key and not the biggest key would be a useful feature.

Unfortunately it's infeasible for now, as bbolt only supports one index (the key being sorted in ascending order by default). But you can workaround it in your application level. For example, you can assign an incremental key for each K/V pair, and get all data included in a struct and marshal it into a []byte as the value.

**Comment by baxiry** [comment]
I got it. thanks
