### ISSUE TITLE
Updating file

### ISSUE THREAD

**Issue by aryehlev** [etcd-io/bbolt#858]
Bbolt seems like a great option for what I need the issue is that I have an offline process that will probably update the file every hour or so.
Is it possible to just change the underlying file? Or would I need to put a lock on the db and reset it?

**Comment by ahrtr** [comment]
You can update the db file directly, as long as there is no other processes (including bbolt) which open the db file.

But it isn't recommended. The db file is supposed to be only managed by bbolt.
