### ISSUE TITLE
Request documentation for checking if bucket exists

### ISSUE THREAD

**Issue by utdrmac** [etcd-io/bbolt#97]
None of the example code in the README shows how to properly check if a bucket exists. All sample code says "assume bucket exists."

Please add at least one code example to demonstrate checking if a bucket exists.

**Comment by m3ng9i** [comment]
There is the document: <https://godoc.org/github.com/coreos/bbolt#Tx.Bucket>

> func (tx *Tx) Bucket(name []byte) *Bucket
> Bucket retrieves a bucket by name. Returns nil if the bucket does not exist. The bucket instance is only valid for the lifetime of the transaction.
