### ISSUE TITLE
Open a not-exist file as read-only mode will cause create file.

### ISSUE THREAD

**Issue by m3ng9i** [etcd-io/bbolt#98]
If I open a database file which is not exist, bolt will return an error and create the file even if `Options.ReadOnly == true`. Why bolt still create file under read-only mode?

Here is the code:

```go
// test-open-file.go
package main

import (
    "fmt"
    "flag"
    "os"
    bolt "github.com/coreos/bbolt"
)

func check(filename string) (err error) {
    db, err := bolt.Open(filename, 0600, &bolt.Options{ReadOnly:true})
    if err != nil {
        return
    }
    defer db.Close()
    return
}

func main() {
    flag.Parse()
    args := flag.Args()
    if len(args) == 0 {
        fmt.Fprintln(os.Stderr, "Please input filename")
        os.Exit(1)
    }

    fmt.Printf("Open \"%s\"\n", args[0])
    if err := check(args[0]); err != nil {
        fmt.Fprintln(os.Stderr, err)
        os.Exit(1)
    }
    fmt.Println("ok")
}
```

Run the code:

    go run test-open-file.go a-not-exist-file.db

Under Windows, it will create two files: a-not-exist-file.db and a-not-exist-file.db.lock. The error message is:

    CreateFileMapping: Not enough storage is available to process this command.

Under Linux, it will create one file: a-not-exist-file.db. The error message is:

    write a-not-exist-file.db: bad file descriptor

The error messages above are not friendly, why not just return "file not exist"?

**Comment by tmm1** [comment]
Ping? Is there any option to prevent this behavior?

**Comment by HarikrishnanBalagopal** [comment]
@m3ng9i
```go
	bolt "github.com/coreos/bbolt"
```
That doesn't seem right. Shouldn't it be
```go
	bolt "go.etcd.io/bbolt"
```
